spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=quertimizer
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_schema: quertimizer
        format_sql: true
  elasticsearch:
    uris: https://localhost:9200
    username: ${ELASTICSEARCH_USERNAME:elastic}
    password: ${ELASTICSEARCH_PASSWORD:n*ncKKdjtxMcqPjqKFGY}
    connection-timeout: 5s
    socket-timeout: 30s
    restclient:
      ssl:
        bundle: elasticsearch-test
  ssl:
    bundle:
      pem:
        elasticsearch-test:
          truststore:
            certificate: "${ELASTICSEARCH_CA_CERT:file:///C:/Users/uusei/Downloads/elasticsearch-9.3.2-windows-x86_64/elasticsearch-9.3.2/config/certs/http_ca.crt}"
