export interface DefaultUiTextDefinition {
  key: string;
  value: string;
  description: string;
}

export const defaultUiTexts: ReadonlyArray<DefaultUiTextDefinition> = [
  { key: "TITLE", value: "쿼티마이저", description: "사이트 제목" },
  { key: "PAGE_TITLE_FORMAT", value: "{page} | {site}", description: "브라우저 탭 제목 형식" },
  { key: "PAGE_TITLE_DASHBOARD", value: "대시보드", description: "브라우저 탭 대시보드 제목" },
  { key: "PAGE_TITLE_PROBLEMS", value: "문제", description: "브라우저 탭 문제 목록 제목" },
  { key: "PAGE_TITLE_PROBLEM_DETAIL", value: "문제 {problemId}", description: "브라우저 탭 문제 상세 제목" },
  { key: "PAGE_TITLE_SUBMISSIONS", value: "제출 목록", description: "브라우저 탭 제출 목록 제목" },
  { key: "PAGE_TITLE_FAVORITES", value: "즐겨찾기", description: "브라우저 탭 즐겨찾기 제목" },
  { key: "PAGE_TITLE_RANKING", value: "랭킹", description: "브라우저 탭 랭킹 제목" },
  { key: "PAGE_TITLE_COMMUNITY", value: "커뮤니티", description: "브라우저 탭 커뮤니티 제목" },
  { key: "PAGE_TITLE_COMMUNITY_DETAIL", value: "커뮤니티 게시글", description: "브라우저 탭 커뮤니티 상세 제목" },
  { key: "PAGE_TITLE_COMMUNITY_WRITE", value: "게시글 작성", description: "브라우저 탭 게시글 작성 제목" },
  { key: "PAGE_TITLE_COMMUNITY_EDIT", value: "게시글 수정", description: "브라우저 탭 게시글 수정 제목" },
  { key: "PAGE_TITLE_ADMIN", value: "관리자", description: "브라우저 탭 관리자 제목" },
  { key: "PAGE_TITLE_PROFILE", value: "프로필", description: "브라우저 탭 프로필 제목" },
  { key: "PAGE_TITLE_PROFILE_HANDLE", value: "{handle} 프로필", description: "브라우저 탭 사용자 프로필 제목" },
  { key: "PAGE_TITLE_PROFILE_ACTIVITY", value: "활동 기록", description: "브라우저 탭 활동 기록 제목" },
  { key: "PAGE_TITLE_PROFILE_ACTIVITY_HANDLE", value: "{handle} 활동 기록", description: "브라우저 탭 사용자 활동 기록 제목" },
  { key: "PAGE_TITLE_NOT_FOUND", value: "찾을 수 없는 페이지", description: "브라우저 탭 404 제목" },
  { key: "NOTIFICATION", value: "쿼티마이저의 새로운 소식을 확인하세요.", description: "헤더 전광판" },
  { key: "COMMON_CONFIRM_BUTTON", value: "확인", description: "공통 확인 버튼" },
  { key: "COMMON_CANCEL_BUTTON", value: "취소", description: "공통 취소 버튼" },
  { key: "COMMON_SAVE_BUTTON", value: "저장", description: "공통 저장 버튼" },
  { key: "COMMON_EDIT_BUTTON", value: "수정", description: "공통 수정 버튼" },
  { key: "COMMON_DELETE_BUTTON", value: "삭제", description: "공통 삭제 버튼" },
  { key: "COMMON_ADD_BUTTON", value: "추가", description: "공통 추가 버튼" },
  { key: "COMMON_CLOSE_BUTTON", value: "닫기", description: "공통 닫기 버튼" },
  { key: "COMMON_SEARCH_BUTTON", value: "검색", description: "공통 검색 버튼" },
  { key: "COMMON_PREVIOUS_BUTTON", value: "이전", description: "공통 이전 버튼" },
  { key: "COMMON_NEXT_BUTTON", value: "다음", description: "공통 다음 버튼" },
  { key: "COMMON_LOADING_STATUS", value: "로딩 중", description: "공통 로딩 상태" },
  { key: "COMMON_EXPAND_ACTION", value: "펼치기", description: "공통 펼치기 버튼" },
  { key: "COMMON_COLLAPSE_ACTION", value: "접기", description: "공통 접기 버튼" },
  { key: "COMMON_NONE_LABEL", value: "없음", description: "공통 없음 표시" },
  { key: "COMMON_PUBLIC_LABEL", value: "공개", description: "공통 공개 선택" },
  { key: "COMMON_PRIVATE_LABEL", value: "비공개", description: "공통 비공개 선택" },
  { key: "COMMON_POSTGRESQL_LABEL", value: "PostgreSQL", description: "공통 PostgreSQL 표시" },
  { key: "COMMON_MYSQL_LABEL", value: "MySQL", description: "공통 MySQL 표시" },
  { key: "COMMON_AND_LABEL", value: "AND", description: "공통 AND 옵션" },
  { key: "COMMON_OR_LABEL", value: "OR", description: "공통 OR 옵션" },
  { key: "COMMON_HINT_LABEL", value: "Hint", description: "공통 Hint 표시" },
  { key: "COMMON_PAGE_LOAD_FAILURE_MESSAGE", value: "잠시 후 다시 시도해주세요.", description: "공통 페이지 오류 안내" },
  { key: "COMMON_STATUS_DIALOG_LABEL", value: "상태 안내", description: "공통 상태 팝업 제목" },
  { key: "COMMON_KEY_LABEL", value: "key", description: "설정 키 헤더" },
  { key: "COMMON_VALUE_LABEL", value: "value", description: "설정 값 헤더" },
  { key: "COMMON_LANGUAGE_LABEL", value: "language", description: "설정 언어 헤더" },
  { key: "COMMON_DESCRIPTION_LABEL", value: "description", description: "설정 설명 헤더" },
  { key: "COMMON_TYPE_LABEL", value: "type", description: "설정 타입 헤더" },
  { key: "COMMON_SENTENCE_LABEL", value: "sentence", description: "설정 문장 헤더" },
  { key: "COMMON_HANDLE_LABEL", value: "Handle", description: "공통 Handle 표시" },
  { key: "COMMON_COST_LABEL", value: "Cost", description: "공통 Cost 표시" },
  { key: "COMMON_SQL_LABEL", value: "SQL", description: "공통 SQL 표시" },
  { key: "COMMON_COMPLETE_LABEL", value: "완료", description: "공통 완료 표시" },
  { key: "COMMON_APPLY_BUTTON", value: "적용", description: "공통 적용 버튼" },
  { key: "COMMON_APPLYING_LABEL", value: "적용 중", description: "공통 적용 중 상태" },
  { key: "COMMON_PROCESSING_LABEL", value: "처리 중…", description: "공통 처리 중 상태" },
  { key: "COMMON_SENDING_LABEL", value: "전송 중", description: "공통 전송 중 상태" },
  { key: "COMMON_VERIFYING_LABEL", value: "확인 중", description: "공통 확인 중 상태" },
  { key: "COMMON_IMAGE_LABEL", value: "이미지", description: "공통 이미지 표시" },
  { key: "COMMON_CONTENT_LABEL", value: "내용", description: "공통 내용 표시" },
  { key: "COMMON_DATE_LABEL", value: "날짜", description: "공통 날짜 표시" },
  { key: "HEADER_NOTICE_LABEL", value: "긴급 공지", description: "헤더 공지 레이블" },
  { key: "HEADER_HOME_LINK_LABEL", value: "Quertimizer 홈으로 이동", description: "헤더 홈 링크" },
  { key: "HEADER_MENU_PROBLEMS", value: "문제", description: "헤더 메뉴 문제" },
  { key: "HEADER_MENU_SUBMISSIONS", value: "제출 목록", description: "헤더 메뉴 제출 목록" },
  { key: "HEADER_MENU_RANKING", value: "랭킹", description: "헤더 메뉴 랭킹" },
  { key: "HEADER_MENU_COMMUNITY", value: "커뮤니티", description: "헤더 메뉴 커뮤니티" },
  { key: "HEADER_MENU_ADMIN", value: "관리자", description: "헤더 메뉴 관리자" },
  { key: "HEADER_ALARM_LIST_TITLE", value: "알림 목록", description: "헤더 알림 목록 링크" },
  { key: "HEADER_ALARM_MARK_ALL_READ_BUTTON", value: "모두 읽음", description: "헤더 알림 모두 읽음" },
  { key: "HEADER_ALARM_EMPTY_STATE", value: "알림이 없습니다.", description: "헤더 알람 빈 상태" },
  { key: "HEADER_FAVORITES_EMPTY_STATE", value: "즐겨찾기한 페이지가 없습니다.", description: "헤더 즐겨찾기 빈 상태" },
  { key: "HEADER_PROFILE_BUTTON", value: "프로필", description: "헤더 프로필 버튼" },
  { key: "HEADER_LOGOUT_BUTTON", value: "로그아웃", description: "헤더 로그아웃 버튼" },
  { key: "HEADER_LOGIN_BUTTON", value: "로그인", description: "헤더 로그인 버튼" },
  { key: "AUTH_SESSION_EXPIRED_MESSAGE", value: "로그인 세션이 만료되었습니다. 다시 로그인해 주세요.", description: "세션 만료 로그인 안내" },
  { key: "HTTP_UNAUTHORIZED_ERROR_MESSAGE", value: "로그인이 필요합니다. 다시 로그인해 주세요.", description: "401 인증 필요 안내" },
  { key: "HTTP_FORBIDDEN_ERROR_MESSAGE", value: "접근 권한이 없습니다.", description: "403 권한 없음 안내" },
  { key: "HTTP_NOT_FOUND_ERROR_MESSAGE", value: "요청한 정보를 찾을 수 없습니다.", description: "404 정보 없음 안내" },
  { key: "HTTP_SERVER_ERROR_MESSAGE", value: "서버 오류가 발생했습니다. 잠시 후 다시 시도해 주세요.", description: "5xx 서버 오류 안내" },
  { key: "ADMIN_UI_TEXT_TAB", value: "UI 텍스트 설정", description: "관리자 UI 텍스트 탭" },
  { key: "ADMIN_ALARM_TEMPLATE_TAB", value: "알람 템플릿 설정", description: "관리자 알람 템플릿 탭" },
  { key: "ADMIN_ALARM_SEND_TAB", value: "알람 전송", description: "관리자 알람 전송 탭" },
  { key: "ADMIN_PERMISSION_TAB", value: "권한 설정", description: "관리자 권한 탭" },
  { key: "ADMIN_ANOMALY_TAB", value: "이상계정 감지", description: "관리자 이상계정 탭" },
  { key: "ADMIN_ACCESS_DENIED_MESSAGE", value: "관리자만 접근할 수 있습니다.", description: "관리자 접근 제한" },
  { key: "GLOBAL_CONFIG_EMPTY_STATE", value: "등록된 UI 텍스트가 없습니다.", description: "UI 텍스트 빈 상태" },
  { key: "GLOBAL_CONFIG_TABLE_LABEL", value: "UI 텍스트 목록", description: "UI 텍스트 테이블 제목" },
  { key: "GLOBAL_CONFIG_CREATE_FAIL_MESSAGE", value: "UI 텍스트를 생성하지 못했습니다.", description: "UI 텍스트 생성 오류" },
  { key: "GLOBAL_CONFIG_UPDATE_FAIL_MESSAGE", value: "UI 텍스트를 수정하지 못했습니다.", description: "UI 텍스트 수정 오류" },
  { key: "GLOBAL_CONFIG_DELETE_FAIL_MESSAGE", value: "UI 텍스트를 삭제하지 못했습니다.", description: "UI 텍스트 삭제 오류" },
  { key: "GLOBAL_CONFIG_SEARCH_LABEL", value: "UI 텍스트 검색", description: "UI 텍스트 검색" },
  { key: "GLOBAL_CONFIG_SEARCH_PLACEHOLDER", value: "key, value, description 검색", description: "UI 텍스트 검색 입력" },
  { key: "GLOBAL_CONFIG_SEARCH_EMPTY_STATE", value: "검색 결과가 없습니다.", description: "UI 텍스트 검색 빈 상태" },
  { key: "GLOBAL_CONFIG_PAGE_LABEL", value: "UI 텍스트 페이지", description: "UI 텍스트 페이지" },
  { key: "GLOBAL_CONFIG_PAGE_INPUT_LABEL", value: "이동할 UI 텍스트 페이지 입력", description: "UI 텍스트 페이지 입력" },
  { key: "GLOBAL_CONFIG_PAGE_INPUT_OPEN_LABEL", value: "이동할 UI 텍스트 페이지 입력 열기", description: "UI 텍스트 페이지 입력 열기" },
  { key: "ALARM_TEMPLATE_EMPTY_STATE", value: "등록된 알람 템플릿이 없습니다.", description: "알람 템플릿 빈 상태" },
  { key: "ALARM_TEMPLATE_TABLE_LABEL", value: "알람 템플릿 목록", description: "알람 템플릿 테이블" },
  { key: "ALARM_TEMPLATE_UPDATE_FAIL_MESSAGE", value: "알람 템플릿을 수정하지 못했습니다.", description: "알람 템플릿 수정 오류" },
  { key: "AUTH_MANAGE_ADMIN_LABEL", value: "Admin", description: "권한 설정 Admin 역할" },
  { key: "AUTH_MANAGE_USER_LABEL", value: "User", description: "권한 설정 User 역할" },
  { key: "AUTH_MANAGE_ADMIN_NOTE", value: "전체 권한", description: "권한 설정 Admin 비고" },
  { key: "AUTH_MANAGE_USER_NOTE", value: "일반 사용자", description: "권한 설정 User 비고" },
  { key: "AUTH_MANAGE_ROLE_SAVE_FAIL_MESSAGE", value: "역할을 저장하지 못했습니다.", description: "권한 설정 역할 저장 오류" },
  { key: "AUTH_MANAGE_ROLE_COLUMN_LABEL", value: "역할", description: "권한 설정 역할 헤더" },
  { key: "AUTH_MANAGE_NOTE_COLUMN_LABEL", value: "비고", description: "권한 설정 비고 헤더" },
  { key: "AUTH_MANAGE_EMPTY_STATE", value: "표시할 계정이 없습니다.", description: "권한 설정 빈 상태" },
  { key: "ALARM_SEND_RECIPIENT_REQUIRED_MESSAGE", value: "수신자 선택은 필수입니다.", description: "알람 전송 수신자 검증" },
  { key: "ALARM_SEND_CONTENT_REQUIRED_MESSAGE", value: "알림 내용 입력은 필수입니다.", description: "알람 전송 내용 검증" },
  { key: "ALARM_SEND_SUCCESS_TOAST", value: "알림을 전송했습니다.", description: "알람 전송 완료 토스트" },
  { key: "ALARM_SEND_FAIL_MESSAGE", value: "알림 전송에 실패했습니다.", description: "알람 전송 오류" },
  { key: "ALARM_SEND_RECIPIENT_LABEL", value: "수신자", description: "알람 전송 수신자 라벨" },
  { key: "ALARM_SEND_HANDLE_PLACEHOLDER", value: "Handle 검색", description: "알람 전송 Handle 검색" },
  { key: "ALARM_SEND_SEARCHING_STATE", value: "검색 중", description: "알람 전송 검색 중 상태" },
  { key: "ALARM_SEND_EMPTY_SEARCH_RESULT", value: "검색 결과가 없습니다.", description: "알람 전송 검색 빈 상태" },
  { key: "ALARM_SEND_CONTENT_LABEL", value: "내용", description: "알람 전송 내용 라벨" },
  { key: "ALARM_SEND_CONTENT_PLACEHOLDER", value: "보낼 알람 내용을 입력", description: "알람 전송 내용 입력" },
  { key: "ALARM_SEND_BUTTON", value: "보내기", description: "알람 전송 버튼" },
  { key: "ANOMALY_TREND_TAB_LABEL", value: "실행/제출 추이", description: "이상계정 추이 탭" },
  { key: "ANOMALY_BLOCKED_USERS_TAB_LABEL", value: "차단 계정 목록", description: "이상계정 차단 계정 탭" },
  { key: "ANOMALY_BLOCKED_IPS_TAB_LABEL", value: "차단 IP 목록", description: "이상계정 차단 IP 탭" },
  { key: "ANOMALY_RANGE_10M_LABEL", value: "최근 10분", description: "이상계정 최근 10분" },
  { key: "ANOMALY_RANGE_1H_LABEL", value: "최근 1시간", description: "이상계정 최근 1시간" },
  { key: "ANOMALY_RANGE_24H_LABEL", value: "최근 24시간", description: "이상계정 최근 24시간" },
  { key: "ANOMALY_RANGE_ALL_LABEL", value: "전체", description: "이상계정 전체 범위" },
  { key: "ANOMALY_RANGE_CUSTOM_LABEL", value: "사용자 지정", description: "이상계정 사용자 지정 범위" },
  { key: "ANOMALY_RANGE_FORMAT_FAIL_MESSAGE", value: "YYYY-MM-DD HH24:Mi 형식으로 입력해 주세요.", description: "이상계정 범위 형식 오류" },
  { key: "ANOMALY_RANGE_ORDER_FAIL_MESSAGE", value: "시작 일시는 종료 일시보다 늦을 수 없습니다.", description: "이상계정 범위 순서 오류" },
  { key: "ANOMALY_ACTION_TYPE_COLUMN_LABEL", value: "실행/제출", description: "이상계정 추이 헤더" },
  { key: "ANOMALY_COUNT_COLUMN_LABEL", value: "횟수", description: "이상계정 횟수 헤더" },
  { key: "ANOMALY_BLOCK_ACTION_LABEL", value: "차단", description: "이상계정 차단 버튼 툴팁" },
  { key: "ANOMALY_EMPTY_STATE", value: "표시할 데이터가 없습니다.", description: "이상계정 빈 상태" },
  { key: "ANOMALY_ALREADY_BLOCKED_LABEL", value: "이미 차단된 계정", description: "이상계정 차단 완료 상태" },
  { key: "ANOMALY_ALREADY_BLOCKED_TITLE", value: "이미 차단됨", description: "이상계정 차단 완료 툴팁" },
  { key: "ANOMALY_BLOCK_TITLE", value: "계정 차단", description: "이상계정 차단 툴팁" },
  { key: "ANOMALY_BLOCKED_AT_COLUMN_LABEL", value: "차단 일시", description: "이상계정 차단 일시 헤더" },
  { key: "ANOMALY_UNBLOCK_TITLE", value: "차단 해제", description: "이상계정 차단 해제 툴팁" },
  { key: "ANOMALY_BLOCKED_USERS_EMPTY_STATE", value: "차단된 계정이 없습니다.", description: "차단 계정 빈 상태" },
  { key: "ANOMALY_BLOCKED_IPS_EMPTY_STATE", value: "차단된 IP가 없습니다.", description: "차단 IP 빈 상태" },
  { key: "FAVORITE_PAGE_TITLE", value: "즐겨찾기", description: "즐겨찾기 페이지 제목" },
  { key: "FAVORITE_SELECT_EMPTY_STATE", value: "즐겨찾기 탭을 선택해 이동하세요.", description: "즐겨찾기 선택 안내" },
  { key: "FAVORITE_EMPTY_HELP", value: "상단 탭 오른쪽 별 아이콘으로 즐겨찾기를 추가하세요.", description: "즐겨찾기 빈 상태 안내" },
  { key: "HOME_PROBLEM_SEARCH_PLACEHOLDER", value: "문제 번호, 제목 검색", description: "문제 목록 검색 입력" },
  { key: "HOME_NOSQL_META", value: "준비 중인 영역", description: "홈 NoSQL 안내 상단" },
  { key: "HOME_NOSQL_TITLE", value: "NoSQL 트랙", description: "홈 NoSQL 제목" },
  { key: "HOME_NOSQL_BADGE", value: "Coming Soon", description: "홈 NoSQL 배지" },
  { key: "HOME_NOSQL_DESC", value: "문서형 데이터 모델, 샤딩 구조, NoSQL 전용 성능 문제 세트는 다음 단계에서 공개될 예정입니다.", description: "홈 NoSQL 안내" },
  { key: "PROBLEM_TABLE_STATUS_COLUMN_LABEL", value: "해결여부", description: "문제 목록 해결 상태 헤더" },
  { key: "PROBLEM_TABLE_SOLVED_LABEL", value: "해결", description: "문제 목록 해결 상태" },
  { key: "PROBLEM_TABLE_UNSOLVED_LABEL", value: "미해결", description: "문제 목록 미해결 상태" },
  { key: "PROBLEM_TABLE_NUMBER_COLUMN_LABEL", value: "문제번호", description: "문제 목록 번호 헤더" },
  { key: "PROBLEM_TABLE_TITLE_COLUMN_LABEL", value: "문제 제목", description: "문제 목록 제목 헤더" },
  { key: "PROBLEM_TABLE_SOLVED_COUNT_COLUMN_LABEL", value: "푼 사람 수", description: "문제 목록 푼 사람 수 헤더" },
  { key: "PROBLEM_TABLE_TOTAL_SUBMIT_COLUMN_LABEL", value: "전체 제출", description: "문제 목록 전체 제출 헤더" },
  { key: "PROBLEM_TABLE_SUCCESS_SUBMIT_COLUMN_LABEL", value: "정답 제출", description: "문제 목록 정답 제출 헤더" },
  { key: "PROBLEM_TABLE_COST_SPREAD_COLUMN_LABEL", value: "Cost 편차", description: "문제 목록 Cost 편차 헤더" },
  { key: "PROBLEM_TABLE_STATS_COLUMN_LABEL", value: "통계", description: "문제 목록 통계 헤더" },
  { key: "PROBLEM_TABLE_EMPTY_STATE", value: "선택한 조건에 맞는 문제가 없습니다.", description: "문제 목록 빈 상태" },
  { key: "PROBLEM_COST_SPREAD_APPLY_LABEL", value: "Cost 편차 적용", description: "문제 목록 Cost 편차 적용" },
  { key: "PROBLEM_COST_SPREAD_SORT_ASC_LABEL", value: "Cost 편차 오름차순", description: "문제 목록 Cost 편차 오름차순" },
  { key: "PROBLEM_COST_SPREAD_SORT_DESC_LABEL", value: "Cost 편차 내림차순", description: "문제 목록 Cost 편차 내림차순" },
  { key: "PROBLEM_COST_SPREAD_SORT_NONE_LABEL", value: "Cost 편차 정렬 없음", description: "문제 목록 Cost 편차 기본 정렬" },
  { key: "PROBLEM_COST_SPREAD_MIN_LABEL", value: "Cost 편차 최소값", description: "문제 목록 Cost 편차 최소값" },
  { key: "PROBLEM_COST_SPREAD_MAX_LABEL", value: "Cost 편차 최대값", description: "문제 목록 Cost 편차 최대값" },
  { key: "PROBLEM_COST_SPREAD_MIN_INPUT_LABEL", value: "Cost 편차 최소 입력값", description: "문제 목록 Cost 편차 최소 입력" },
  { key: "PROBLEM_COST_SPREAD_MAX_INPUT_LABEL", value: "Cost 편차 최대 입력값", description: "문제 목록 Cost 편차 최대 입력" },
  { key: "PROBLEM_COST_SPREAD_RANGE_INPUT_LABEL", value: "Cost 편차 범위 직접 입력", description: "문제 목록 Cost 편차 직접 입력" },
  { key: "RUNTIME_UNUSED_LABEL", value: "미사용", description: "실행 계획 Hint 미사용" },
  { key: "RUNTIME_USED_LABEL", value: "사용", description: "실행 계획 Hint 사용" },
  { key: "RUNTIME_FASTEST_LABEL", value: "1st", description: "런타임 최고 기록" },
  { key: "RUNTIME_MY_RECORD_LABEL", value: "내 기록", description: "런타임 차트 내 기록" },
  { key: "RUNTIME_RATIO_SUFFIX_LABEL", value: "{label} 발생 비율", description: "런타임 비율 라벨" },
  { key: "RUNTIME_HINT_RATIO_LABEL", value: "Hint 사용 비율", description: "런타임 Hint 비율" },
  { key: "RUNTIME_BUCKET_COUNT_LABEL", value: "{count}명", description: "런타임 버킷 인원 수" },
  { key: "RUNTIME_SAMPLE_COUNT_LABEL", value: "집계 수", description: "런타임 집계 수" },
  { key: "RUNTIME_AVERAGE_COST_LABEL", value: "평균 Cost", description: "런타임 평균 Cost" },
  { key: "RUNTIME_MINIMUM_COST_LABEL", value: "최소 Cost", description: "런타임 최소 Cost" },
  { key: "RUNTIME_MEDIAN_COST_LABEL", value: "Cost 중앙값", description: "런타임 Cost 중앙값" },
  { key: "RUNTIME_EMPTY_STATE", value: "선택한 조건에 맞는 제출이 없습니다.", description: "런타임 차트 빈 상태" },
  { key: "RUNTIME_SUMMARY_PANEL_LABEL", value: "통계 개요", description: "런타임 통계 개요" },
  { key: "RUNTIME_COST_DISTRIBUTION_LABEL", value: "Cost 분포", description: "런타임 Cost 분포" },
  { key: "RUNTIME_FILTER_OPEN_LABEL", value: "실행 계획 요소 열기", description: "런타임 필터 열기" },
  { key: "RUNTIME_FILTER_TITLE", value: "실행 계획 요소", description: "런타임 필터 제목" },
  { key: "RUNTIME_FILTER_MATCH_MODE_LABEL", value: "필터 조합 방식", description: "런타임 필터 조합 방식" },
  { key: "RUNTIME_FILTER_CANCEL_LABEL", value: "실행 계획 요소 필터 취소", description: "런타임 필터 취소" },
  { key: "RUNTIME_FILTER_APPLY_LABEL", value: "실행 계획 요소 필터 적용", description: "런타임 필터 적용" },
  { key: "RUNTIME_FILTER_DETAIL_GROUP_LABEL", value: "실행 계획 요소 세부 선택", description: "런타임 필터 상세 선택" },
  { key: "RUNTIME_FILTER_SUMMARY_EXTRA_LABEL", value: "외 {count}", description: "런타임 필터 추가 요약" },
  { key: "RUNTIME_PLAN_ELEMENT_EMPTY_LABEL", value: "요소 없음", description: "런타임 요소 없음" },
  { key: "RUNTIME_PLAN_ELEMENT_COUNT_LABEL", value: "요소 {count}개", description: "런타임 요소 개수" },
  { key: "RUNTIME_ALL_LABEL", value: "전체", description: "런타임 전체 선택" },
  { key: "RUNTIME_SCAN_LABEL", value: "Scan", description: "런타임 Scan 분류" },
  { key: "RUNTIME_JOIN_LABEL", value: "Join", description: "런타임 Join 분류" },
  { key: "RUNTIME_FILTER_LABEL", value: "Filter", description: "런타임 Filter 분류" },
  { key: "RUNTIME_SORT_LABEL", value: "Sort", description: "런타임 Sort 분류" },
  { key: "RUNTIME_AGGREGATE_LABEL", value: "Aggregate", description: "런타임 Aggregate 분류" },
  { key: "RUNTIME_FULL_SCAN_LABEL", value: "FULL_SCAN", description: "런타임 FULL_SCAN 옵션" },
  { key: "RUNTIME_FULL_TABLE_SCAN_LABEL", value: "FULL_TABLE_SCAN", description: "런타임 FULL_TABLE_SCAN 옵션" },
  { key: "RUNTIME_INDEX_SCAN_LABEL", value: "INDEX_SCAN", description: "런타임 INDEX_SCAN 옵션" },
  { key: "RUNTIME_BITMAP_SCAN_LABEL", value: "BITMAP_SCAN", description: "런타임 BITMAP_SCAN 옵션" },
  { key: "RUNTIME_TID_SCAN_LABEL", value: "TID_SCAN", description: "런타임 TID_SCAN 옵션" },
  { key: "RUNTIME_RANGE_SCAN_LABEL", value: "RANGE_SCAN", description: "런타임 RANGE_SCAN 옵션" },
  { key: "RUNTIME_REF_SCAN_LABEL", value: "REF_SCAN", description: "런타임 REF_SCAN 옵션" },
  { key: "RUNTIME_CONST_SCAN_LABEL", value: "CONST_SCAN", description: "런타임 CONST_SCAN 옵션" },
  { key: "RUNTIME_DERIVED_SCAN_LABEL", value: "DERIVED_SCAN", description: "런타임 DERIVED_SCAN 옵션" },
  { key: "RUNTIME_NESTED_LOOP_LABEL", value: "NESTED_LOOP", description: "런타임 NESTED_LOOP 옵션" },
  { key: "RUNTIME_MERGE_JOIN_LABEL", value: "MERGE_JOIN", description: "런타임 MERGE_JOIN 옵션" },
  { key: "RUNTIME_HASH_JOIN_LABEL", value: "HASH_JOIN", description: "런타임 HASH_JOIN 옵션" },
  { key: "RUNTIME_JOIN_BUFFER_LABEL", value: "JOIN_BUFFER", description: "런타임 JOIN_BUFFER 옵션" },
  { key: "RUNTIME_ACCESS_FILTER_LABEL", value: "ACCESS_FILTER", description: "런타임 ACCESS_FILTER 옵션" },
  { key: "RUNTIME_POST_FILTER_LABEL", value: "POST_FILTER", description: "런타임 POST_FILTER 옵션" },
  { key: "RUNTIME_JOIN_FILTER_LABEL", value: "JOIN_FILTER", description: "런타임 JOIN_FILTER 옵션" },
  { key: "RUNTIME_INDEX_CONDITION_LABEL", value: "INDEX_CONDITION", description: "런타임 INDEX_CONDITION 옵션" },
  { key: "RUNTIME_ATTACHED_CONDITION_LABEL", value: "ATTACHED_CONDITION", description: "런타임 ATTACHED_CONDITION 옵션" },
  { key: "RUNTIME_FILTER_CONDITION_LABEL", value: "FILTER_CONDITION", description: "런타임 FILTER_CONDITION 옵션" },
  { key: "RUNTIME_PLAIN_SORT_LABEL", value: "PLAIN_SORT", description: "런타임 PLAIN_SORT 옵션" },
  { key: "RUNTIME_INCREMENTAL_SORT_LABEL", value: "INCREMENTAL_SORT", description: "런타임 INCREMENTAL_SORT 옵션" },
  { key: "RUNTIME_FILESORT_LABEL", value: "FILESORT", description: "런타임 FILESORT 옵션" },
  { key: "RUNTIME_TEMPORARY_TABLE_LABEL", value: "TEMPORARY_TABLE", description: "런타임 TEMPORARY_TABLE 옵션" },
  { key: "RUNTIME_PLAIN_AGG_LABEL", value: "PLAIN_AGG", description: "런타임 PLAIN_AGG 옵션" },
  { key: "RUNTIME_GROUP_AGG_LABEL", value: "GROUP_AGG", description: "런타임 GROUP_AGG 옵션" },
  { key: "RUNTIME_HASH_AGG_LABEL", value: "HASH_AGG", description: "런타임 HASH_AGG 옵션" },
  { key: "RUNTIME_MIXED_AGG_LABEL", value: "MIXED_AGG", description: "런타임 MIXED_AGG 옵션" },
  { key: "RUNTIME_WINDOW_AGG_LABEL", value: "WINDOW_AGG", description: "런타임 WINDOW_AGG 옵션" },
  { key: "RUNTIME_UNIQUE_AGG_LABEL", value: "UNIQUE_AGG", description: "런타임 UNIQUE_AGG 옵션" },
  { key: "RUNTIME_SET_AGG_LABEL", value: "SET_AGG", description: "런타임 SET_AGG 옵션" },
  { key: "RUNTIME_GROUPING_OPERATION_LABEL", value: "GROUPING_OPERATION", description: "런타임 GROUPING_OPERATION 옵션" },
  { key: "RUNTIME_WINDOW_OPERATION_LABEL", value: "WINDOW_OPERATION", description: "런타임 WINDOW_OPERATION 옵션" },
  { key: "RUNTIME_AGGREGATE_OPERATION_LABEL", value: "AGGREGATE", description: "런타임 AGGREGATE 옵션" },
  { key: "RUNTIME_OTHERS_LABEL", value: "OTHERS", description: "런타임 OTHERS 옵션" },
  { key: "RUNTIME_FULL_SCAN_DESCRIPTION", value: "인덱스를 타지 않고 테이블 페이지를 순차적으로 읽는 경우를 묶습니다.", description: "런타임 FULL_SCAN 설명" },
  { key: "RUNTIME_FULL_TABLE_SCAN_DESCRIPTION", value: "인덱스를 타지 않고 테이블을 읽는 접근을 묶습니다.", description: "런타임 FULL_TABLE_SCAN 설명" },
  { key: "RUNTIME_INDEX_SCAN_DESCRIPTION", value: "Index Scan, Index Only Scan 계열을 묶습니다.", description: "런타임 INDEX_SCAN 설명" },
  { key: "RUNTIME_BITMAP_SCAN_DESCRIPTION", value: "Bitmap Index Scan + Bitmap Heap Scan 계열을 묶습니다.", description: "런타임 BITMAP_SCAN 설명" },
  { key: "RUNTIME_RANGE_SCAN_DESCRIPTION", value: "범위 조건으로 인덱스를 읽는 접근을 묶습니다.", description: "런타임 RANGE_SCAN 설명" },
  { key: "RUNTIME_REF_SCAN_DESCRIPTION", value: "동등 조건으로 인덱스를 참조하는 접근을 묶습니다.", description: "런타임 REF_SCAN 설명" },
  { key: "RUNTIME_CONST_SCAN_DESCRIPTION", value: "상수로 단일 행을 찾는 접근을 묶습니다.", description: "런타임 CONST_SCAN 설명" },
  { key: "RUNTIME_DERIVED_SCAN_DESCRIPTION", value: "VIEW, WITH, MATERIALIZE 같은 파생 결과 접근을 묶습니다.", description: "런타임 DERIVED_SCAN 설명" },
  { key: "RUNTIME_TID_SCAN_DESCRIPTION", value: "Tid Scan 계열을 묶습니다.", description: "런타임 TID_SCAN 설명" },
  { key: "RUNTIME_NESTED_LOOP_DESCRIPTION", value: "바깥 결과를 기준으로 안쪽 경로를 반복 탐색하는 조인입니다.", description: "런타임 NESTED_LOOP 설명" },
  { key: "RUNTIME_MERGE_JOIN_DESCRIPTION", value: "정렬된 두 입력을 병합하면서 조인하는 방식입니다.", description: "런타임 MERGE_JOIN 설명" },
  { key: "RUNTIME_HASH_JOIN_DESCRIPTION", value: "한쪽 입력으로 해시 테이블을 만들고 다른 쪽을 probe 하는 방식입니다.", description: "런타임 HASH_JOIN 설명" },
  { key: "RUNTIME_JOIN_BUFFER_DESCRIPTION", value: "조인 버퍼를 사용하는 조인 처리를 묶습니다.", description: "런타임 JOIN_BUFFER 설명" },
  { key: "RUNTIME_ACCESS_FILTER_DESCRIPTION", value: "접근 단계에서 읽을 범위를 줄이는 조건을 묶습니다.", description: "런타임 ACCESS_FILTER 설명" },
  { key: "RUNTIME_POST_FILTER_DESCRIPTION", value: "읽은 뒤 추가로 행을 거르는 조건을 묶습니다.", description: "런타임 POST_FILTER 설명" },
  { key: "RUNTIME_JOIN_FILTER_DESCRIPTION", value: "조인 과정에서 적용되는 조건을 묶습니다.", description: "런타임 JOIN_FILTER 설명" },
  { key: "RUNTIME_INDEX_CONDITION_DESCRIPTION", value: "인덱스 조건 푸시다운으로 적용되는 조건을 묶습니다.", description: "런타임 INDEX_CONDITION 설명" },
  { key: "RUNTIME_ATTACHED_CONDITION_DESCRIPTION", value: "테이블 접근 뒤 붙는 조건을 묶습니다.", description: "런타임 ATTACHED_CONDITION 설명" },
  { key: "RUNTIME_FILTER_CONDITION_DESCRIPTION", value: "필터링 단계의 조건을 묶습니다.", description: "런타임 FILTER_CONDITION 설명" },
  { key: "RUNTIME_PLAIN_SORT_DESCRIPTION", value: "일반 Sort 계열을 묶습니다.", description: "런타임 PLAIN_SORT 설명" },
  { key: "RUNTIME_INCREMENTAL_SORT_DESCRIPTION", value: "Incremental Sort 계열을 묶습니다.", description: "런타임 INCREMENTAL_SORT 설명" },
  { key: "RUNTIME_FILESORT_DESCRIPTION", value: "filesort가 필요한 정렬을 묶습니다.", description: "런타임 FILESORT 설명" },
  { key: "RUNTIME_TEMPORARY_TABLE_DESCRIPTION", value: "임시 테이블을 사용하는 처리를 묶습니다.", description: "런타임 TEMPORARY_TABLE 설명" },
  { key: "RUNTIME_PLAIN_AGG_DESCRIPTION", value: "그룹 키 없이 바로 집계하는 단순 집계를 묶습니다.", description: "런타임 PLAIN_AGG 설명" },
  { key: "RUNTIME_GROUP_AGG_DESCRIPTION", value: "정렬된 입력을 기준으로 그룹 집계를 수행하는 경우를 묶습니다.", description: "런타임 GROUP_AGG 설명" },
  { key: "RUNTIME_HASH_AGG_DESCRIPTION", value: "해시 기반 그룹 집계를 묶습니다.", description: "런타임 HASH_AGG 설명" },
  { key: "RUNTIME_MIXED_AGG_DESCRIPTION", value: "해시와 정렬 전략이 섞인 집계 계열입니다.", description: "런타임 MIXED_AGG 설명" },
  { key: "RUNTIME_WINDOW_AGG_DESCRIPTION", value: "윈도 함수 계산과 연결된 집계를 묶습니다.", description: "런타임 WINDOW_AGG 설명" },
  { key: "RUNTIME_UNIQUE_AGG_DESCRIPTION", value: "중복 제거 기반 집계를 묶습니다.", description: "런타임 UNIQUE_AGG 설명" },
  { key: "RUNTIME_SET_AGG_DESCRIPTION", value: "UNION, INTERSECT, EXCEPT 같은 집합 연산 기반 처리를 묶습니다.", description: "런타임 SET_AGG 설명" },
  { key: "RUNTIME_GROUPING_OPERATION_DESCRIPTION", value: "그룹핑 작업을 묶습니다.", description: "런타임 GROUPING_OPERATION 설명" },
  { key: "RUNTIME_WINDOW_OPERATION_DESCRIPTION", value: "윈도우 함수 작업을 묶습니다.", description: "런타임 WINDOW_OPERATION 설명" },
  { key: "RUNTIME_AGGREGATE_OPERATION_DESCRIPTION", value: "집계 작업을 묶습니다.", description: "런타임 AGGREGATE 설명" },
  { key: "RUNTIME_NONE_DESCRIPTION", value: "해당 분류가 없는 실행 계획입니다.", description: "런타임 없음 설명" },
  { key: "RUNTIME_OTHERS_DESCRIPTION", value: "위 분류로 명확히 묶기 어려운 기타 연산입니다.", description: "런타임 기타 설명" },
  { key: "RUNTIME_DEFAULT_DESCRIPTION", value: "실행 계획 설명입니다.", description: "런타임 기본 설명" },
  { key: "SUBMIT_HISTORY_RESULT_CORRECT_LABEL", value: "정답", description: "제출 결과 정답" },
  { key: "SUBMIT_HISTORY_RESULT_WRONG_LABEL", value: "오답", description: "제출 결과 오답" },
  { key: "SUBMIT_HISTORY_RESULT_TITLE", value: "제출 결과", description: "제출 결과 모달 제목" },
  { key: "SUBMIT_HISTORY_PLAN_TITLE", value: "실행 계획 요소", description: "제출 실행 계획 제목" },
  { key: "SUBMIT_HISTORY_SQL_MODAL_LABEL", value: "제출 SQL 보기", description: "제출 SQL 모달" },
  { key: "SUBMIT_HISTORY_SQL_VIEWER_LABEL", value: "제출 SQL", description: "제출 SQL 보기" },
  { key: "SUBMIT_HISTORY_MODAL_CLOSE_LABEL", value: "제출 결과 닫기", description: "제출 결과 닫기" },
  { key: "SUBMIT_HISTORY_PLAN_MODAL_LABEL", value: "실행 계획 요소 보기", description: "제출 실행 계획 모달" },
  { key: "SUBMIT_HISTORY_PLAN_MODAL_CLOSE_LABEL", value: "실행 계획 요소 닫기", description: "제출 실행 계획 닫기" },
  { key: "SUBMIT_HISTORY_PLAN_DETAIL_BUTTON_LABEL", value: "실행 계획 요소 자세히 보기", description: "제출 실행 계획 자세히 보기" },
  { key: "SUBMIT_HISTORY_RESULT_FILTER_MENU_LABEL", value: "제출 결과 필터 옵션", description: "제출 결과 필터 메뉴" },
  { key: "SUBMIT_HISTORY_PLAN_FILTER_MENU_LABEL", value: "실행 계획 요소 필터 옵션", description: "제출 실행 계획 필터 메뉴" },
  { key: "SUBMIT_HISTORY_RESULT_FILTER_GROUP_LABEL", value: "제출 결과 선택", description: "제출 결과 필터 선택" },
  { key: "SUBMIT_HISTORY_PLAN_FILTER_GROUP_LABEL", value: "실행 계획 요소 선택", description: "제출 실행 계획 필터 선택" },
  { key: "SUBMIT_HISTORY_PLAN_MATCH_MODE_LABEL", value: "실행 계획 요소 검색 방식", description: "제출 실행 계획 검색 방식" },
  { key: "SUBMIT_HISTORY_PLAN_SECTION_GROUP_LABEL", value: "실행 계획 요소 선택", description: "제출 실행 계획 영역 선택" },
  { key: "SUBMIT_HISTORY_PLAN_DETAIL_GROUP_LABEL", value: "실행 계획 요소 상세 선택", description: "제출 실행 계획 상세 선택" },
  { key: "SUBMIT_HISTORY_PLAN_EMPTY_STATE", value: "선택한 실행 계획 요소가 없습니다.", description: "제출 실행 계획 빈 상태" },
  { key: "SUBMIT_HISTORY_DBMS_TABLIST_LABEL", value: "제출 목록 DBMS 선택", description: "제출 목록 DBMS 선택" },
  { key: "SUBMIT_HISTORY_FAVORITE_LABEL", value: "제출 목록 / {dbms}", description: "제출 목록 즐겨찾기" },
  { key: "SUBMIT_HISTORY_SUBMIT_ID_PLACEHOLDER", value: "제출번호", description: "제출 목록 제출번호 검색" },
  { key: "SUBMIT_HISTORY_SUBMIT_ID_SEARCH_LABEL", value: "제출번호 검색", description: "제출 목록 제출번호 검색 라벨" },
  { key: "SUBMIT_HISTORY_HANDLE_SEARCH_LABEL", value: "Handle 검색", description: "제출 목록 Handle 검색" },
  { key: "SUBMIT_HISTORY_PROBLEM_ID_PLACEHOLDER", value: "문제번호", description: "제출 목록 문제번호 검색" },
  { key: "SUBMIT_HISTORY_PROBLEM_ID_SEARCH_LABEL", value: "문제번호 검색", description: "제출 목록 문제번호 검색 라벨" },
  { key: "SUBMIT_HISTORY_TABLE_LABEL", value: "제출 이력 목록", description: "제출 목록 테이블" },
  { key: "SUBMIT_HISTORY_SUBMIT_ID_COLUMN_LABEL", value: "제출번호", description: "제출 목록 제출번호 헤더" },
  { key: "SUBMIT_HISTORY_SUBMITTED_AT_COLUMN_LABEL", value: "제출 시각", description: "제출 목록 제출 시각 헤더" },
  { key: "SUBMIT_HISTORY_PLAN_COLUMN_LABEL", value: "실행계획요소", description: "제출 목록 실행계획 헤더" },
  { key: "SUBMIT_HISTORY_RESULT_FILTER_BUTTON_LABEL", value: "제출 결과 필터 열기", description: "제출 결과 필터 열기" },
  { key: "SUBMIT_HISTORY_PLAN_FILTER_BUTTON_LABEL", value: "실행 계획 요소 필터 열기", description: "제출 실행 계획 필터 열기" },
  { key: "SUBMIT_HISTORY_EMPTY_STATE", value: "조건에 맞는 제출 이력이 없습니다.", description: "제출 목록 빈 상태" },
  { key: "SUBMIT_HISTORY_HANDLE_PROFILE_MOVE_LABEL", value: "{handle} 프로필 이동", description: "제출 목록 프로필 이동" },
  { key: "SUBMIT_HISTORY_PROBLEM_MOVE_LABEL", value: "문제 {problemId} 이동", description: "제출 목록 문제 이동" },
  { key: "SUBMIT_HISTORY_PLAN_DETAIL_MOVE_LABEL", value: "{label} 자세히 보기", description: "제출 실행 계획 자세히 보기" },
  { key: "SUBMIT_HISTORY_COST_SORT_ASC_LABEL", value: "Cost 오름차순 정렬", description: "제출 목록 Cost 오름차순" },
  { key: "SUBMIT_HISTORY_COST_SORT_DESC_LABEL", value: "Cost 내림차순 정렬", description: "제출 목록 Cost 내림차순" },
  { key: "SUBMIT_HISTORY_COST_SORT_NONE_LABEL", value: "Cost 정렬 없음", description: "제출 목록 Cost 기본 정렬" },
  { key: "SUBMIT_HISTORY_PAGE_NAV_LABEL", value: "제출 이력 페이지", description: "제출 목록 페이지" },
  { key: "SUBMIT_HISTORY_PAGE_INPUT_LABEL", value: "이동할 제출 이력 페이지 입력", description: "제출 목록 페이지 입력" },
  { key: "SUBMIT_HISTORY_PAGE_INPUT_BUTTON_LABEL", value: "이동할 제출 이력 페이지 입력 열기", description: "제출 목록 페이지 입력 열기" },
  { key: "RANKING_SOLVED_COLUMN_LABEL", value: "해결한 문제", description: "랭킹 해결한 문제 헤더" },
  { key: "RANKING_COST_PERCENTILE_COLUMN_LABEL", value: "평균 Cost 백분위", description: "랭킹 Cost 백분위 헤더" },
  { key: "RANKING_TOTAL_SUBMIT_COLUMN_LABEL", value: "전체 제출 수", description: "랭킹 전체 제출 수 헤더" },
  { key: "RANKING_SUCCESS_SUBMIT_COLUMN_LABEL", value: "정답 제출 수", description: "랭킹 정답 제출 수 헤더" },
  { key: "RANKING_EMPTY_STATE", value: "조건에 맞는 랭킹이 없습니다.", description: "랭킹 빈 상태" },
  { key: "DASHBOARD_HIGHLIGHT_SECTION_TITLE", value: "커뮤니티 하이라이트", description: "대시보드 커뮤니티 제목" },
  { key: "DASHBOARD_ALL_VIEW_BUTTON", value: "전체 보기", description: "대시보드 커뮤니티 전체 보기" },
  { key: "DASHBOARD_RECOMMEND_SECTION_TITLE", value: "추천 문제", description: "대시보드 추천 문제 제목" },
  { key: "DASHBOARD_ALL_PROBLEMS_BUTTON", value: "전체 문제 보기", description: "대시보드 문제 전체 보기" },
  { key: "DASHBOARD_EMPTY_POSTS_STATE", value: "표시할 게시글이 없습니다.", description: "대시보드 게시글 빈 상태" },
  { key: "DASHBOARD_EMPTY_PROBLEMS_STATE", value: "추천할 문제가 없습니다.", description: "대시보드 추천 문제 빈 상태" },
  { key: "DASHBOARD_METRIC_SOLVED_LABEL", value: "해결", description: "대시보드 문제 메트릭 해결" },
  { key: "DASHBOARD_METRIC_SUBMIT_LABEL", value: "제출", description: "대시보드 문제 메트릭 제출" },
  { key: "DASHBOARD_METRIC_CORRECT_LABEL", value: "정답", description: "대시보드 문제 메트릭 정답" },
  { key: "DASHBOARD_POST_REACTION_LABEL", value: "게시글 반응", description: "대시보드 게시글 반응" },
  { key: "DASHBOARD_EXCERPT_EMPTY", value: "본문 미리보기가 없습니다.", description: "대시보드 본문 미리보기 빈 상태" },
  { key: "COMMUNITY_CATEGORY_ALL_LABEL", value: "전체", description: "커뮤니티 전체 탭" },
  { key: "COMMUNITY_CATEGORY_NOTICE_LABEL", value: "공지", description: "커뮤니티 공지 탭" },
  { key: "COMMUNITY_CATEGORY_FREE_LABEL", value: "자유", description: "커뮤니티 자유 탭" },
  { key: "COMMUNITY_CATEGORY_QUESTION_LABEL", value: "질문", description: "커뮤니티 질문 탭" },
  { key: "COMMUNITY_CATEGORY_TIP_LABEL", value: "팁", description: "커뮤니티 팁 탭" },
  { key: "COMMUNITY_LOGIN_REQUIRED_TOOLTIP", value: "로그인 후 글쓰기를 사용할 수 있습니다.", description: "커뮤니티 글쓰기 비활성 안내" },
  { key: "COMMUNITY_WRITE_BUTTON", value: "글쓰기", description: "커뮤니티 글쓰기 버튼" },
  { key: "COMMUNITY_SEARCH_PLACEHOLDER", value: "제목, 작성자, 태그, 내용 검색", description: "커뮤니티 검색 입력" },
  { key: "COMMUNITY_CATEGORY_COLUMN_LABEL", value: "구분", description: "커뮤니티 구분 헤더" },
  { key: "COMMUNITY_TITLE_COLUMN_LABEL", value: "제목", description: "커뮤니티 제목 헤더" },
  { key: "COMMUNITY_DATE_COLUMN_LABEL", value: "작성일", description: "커뮤니티 작성일 헤더" },
  { key: "COMMUNITY_VIEWS_COLUMN_LABEL", value: "조회수", description: "커뮤니티 조회수 헤더" },
  { key: "COMMUNITY_LIKES_COLUMN_LABEL", value: "좋아요", description: "커뮤니티 좋아요 헤더" },
  { key: "COMMUNITY_COMMENTS_COLUMN_LABEL", value: "댓글", description: "커뮤니티 댓글 헤더" },
  { key: "COMMUNITY_EMPTY_STATE", value: "조건에 맞는 게시글이 없습니다.", description: "커뮤니티 빈 상태" },
  { key: "COMMUNITY_POST_DRAFT_LOGIN_DESC", value: "작성 중인 게시글은 유지됩니다. 로그인 후 이어서 작성할 수 있습니다.", description: "커뮤니티 작성 로그인 안내" },
  { key: "COMMUNITY_TAG_LIMIT_MESSAGE", value: "태그는 최대 7개까지 추가할 수 있습니다.", description: "커뮤니티 태그 제한 안내" },
  { key: "COMMUNITY_REQUIRED_FIELDS_MESSAGE", value: "제목과 본문 입력은 필수입니다.", description: "커뮤니티 필수 입력 안내" },
  { key: "COMMUNITY_CONTENT_MAX_BYTES_MESSAGE", value: "본문은 최대 {maxBytes} Byte까지 입력할 수 있습니다.", description: "커뮤니티 본문 길이 제한" },
  { key: "COMMUNITY_UPLOAD_SUCCESS_TOAST", value: "업로드했습니다.", description: "커뮤니티 업로드 성공" },
  { key: "COMMUNITY_UPLOAD_FAIL_TOAST", value: "업로드에 실패했습니다.", description: "커뮤니티 업로드 실패" },
  { key: "COMMUNITY_POST_SAVE_FAIL_MESSAGE", value: "게시글을 저장하지 못했습니다.", description: "커뮤니티 게시글 저장 오류" },
  { key: "COMMUNITY_TITLE_PLACEHOLDER", value: "제목", description: "커뮤니티 제목 입력" },
  { key: "COMMUNITY_TAG_PLACEHOLDER", value: "태그 추가", description: "커뮤니티 태그 입력" },
  { key: "COMMUNITY_TAG_LIMIT_PLACEHOLDER", value: "태그는 최대 7개", description: "커뮤니티 태그 제한 입력" },
  { key: "COMMUNITY_UPLOAD_BUTTON", value: "업로드", description: "커뮤니티 업로드 버튼" },
  { key: "COMMUNITY_COMMENT_LOGIN_DESC", value: "작성 중인 댓글은 유지됩니다. 로그인 후 이어서 작성할 수 있습니다.", description: "커뮤니티 댓글 로그인 안내" },
  { key: "COMMUNITY_REFRESH_FAIL_MESSAGE", value: "게시글을 새로고침하지 못했습니다.", description: "커뮤니티 상세 새로고침 오류" },
  { key: "COMMUNITY_TITLE_REQUIRED_MESSAGE", value: "제목 입력은 필수입니다.", description: "커뮤니티 제목 검증" },
  { key: "COMMUNITY_BODY_REQUIRED_MESSAGE", value: "본문 입력은 필수입니다.", description: "커뮤니티 본문 검증" },
  { key: "COMMUNITY_EDIT_SUCCESS_TOAST", value: "게시글 수정 완료.", description: "커뮤니티 수정 완료" },
  { key: "COMMUNITY_EDIT_FAIL_MESSAGE", value: "게시글을 수정하지 못했습니다.", description: "커뮤니티 수정 오류" },
  { key: "COMMUNITY_POST_LIKE_FAIL_MESSAGE", value: "좋아요 처리에 실패했습니다.", description: "커뮤니티 좋아요 오류" },
  { key: "COMMUNITY_COMMENT_SAVE_FAIL_MESSAGE", value: "댓글을 등록하지 못했습니다.", description: "커뮤니티 댓글 등록 오류" },
  { key: "COMMUNITY_REPLY_SAVE_FAIL_MESSAGE", value: "대댓글을 등록하지 못했습니다.", description: "커뮤니티 대댓글 등록 오류" },
  { key: "COMMUNITY_COMMENT_LIKE_FAIL_MESSAGE", value: "댓글 좋아요 처리에 실패했습니다.", description: "커뮤니티 댓글 좋아요 오류" },
  { key: "COMMUNITY_LINK_COPY_SUCCESS_TOAST", value: "링크 복사 완료.", description: "커뮤니티 링크 복사 완료" },
  { key: "COMMUNITY_LINK_COPY_FAIL_MESSAGE", value: "링크를 복사하지 못했습니다.", description: "커뮤니티 링크 복사 오류" },
  { key: "COMMUNITY_DELETE_CONFIRM_MESSAGE", value: "게시글을 삭제하시겠습니까?", description: "커뮤니티 게시글 삭제 확인" },
  { key: "COMMUNITY_DELETE_FAIL_MESSAGE", value: "게시글을 삭제하지 못했습니다.", description: "커뮤니티 게시글 삭제 오류" },
  { key: "COMMUNITY_TAG_SEARCH_LINK", value: "커뮤니티에서 태그 검색", description: "커뮤니티 태그 검색 링크" },
  { key: "COMMUNITY_MOVE_TO_PROBLEM_LINK", value: "문제로 이동", description: "커뮤니티 문제 이동 링크" },
  { key: "COMMUNITY_UPDATED_PREFIX", value: "수정 {date}", description: "커뮤니티 수정 시각" },
  { key: "COMMUNITY_COMMENTS_TITLE", value: "댓글 {count}개", description: "커뮤니티 댓글 수 제목" },
  { key: "COMMUNITY_COMMENT_PLACEHOLDER", value: "댓글 추가", description: "커뮤니티 댓글 입력" },
  { key: "COMMUNITY_COMMENT_SUBMIT_BUTTON", value: "댓글 등록", description: "커뮤니티 댓글 등록 버튼" },
  { key: "COMMUNITY_IMAGE_LIGHTBOX_TITLE", value: "첨부 이미지 크게 보기", description: "커뮤니티 이미지 확대 제목" },
  { key: "COMMUNITY_EDITOR_IMAGE_ONLY_MESSAGE", value: "이미지 파일만 첨부할 수 있습니다.", description: "커뮤니티 에디터 이미지 검증" },
  { key: "COMMUNITY_EDITOR_IMAGE_UPLOAD_FAIL_MESSAGE", value: "이미지 업로드에 실패했습니다.", description: "커뮤니티 에디터 이미지 업로드 오류" },
  { key: "COMMUNITY_EDITOR_ATTACHED_IMAGE_ALT", value: "첨부 이미지", description: "커뮤니티 첨부 이미지 대체 텍스트" },
  { key: "COMMUNITY_EDITOR_DISCLOSURE_LABEL", value: "요약", description: "커뮤니티 details 요약 라벨" },
  { key: "COMMUNITY_EDITOR_BOLD_TITLE", value: "굵게", description: "커뮤니티 에디터 굵게" },
  { key: "COMMUNITY_EDITOR_STRIKE_TITLE", value: "취소선", description: "커뮤니티 에디터 취소선" },
  { key: "COMMUNITY_EDITOR_UNDERLINE_TITLE", value: "밑줄", description: "커뮤니티 에디터 밑줄" },
  { key: "COMMUNITY_EDITOR_HIGHLIGHT_LABEL", value: "형광", description: "커뮤니티 에디터 형광" },
  { key: "COMMUNITY_EDITOR_HIGHLIGHT_TITLE", value: "하이라이트", description: "커뮤니티 에디터 하이라이트" },
  { key: "COMMUNITY_EDITOR_INLINE_CODE_TITLE", value: "인라인 코드", description: "커뮤니티 에디터 인라인 코드" },
  { key: "COMMUNITY_EDITOR_CODE_BLOCK_TITLE", value: "코드블럭", description: "커뮤니티 에디터 코드블럭" },
  { key: "COMMUNITY_EDITOR_HEADING_LABEL", value: "제목", description: "커뮤니티 에디터 제목" },
  { key: "COMMUNITY_EDITOR_QUOTE_LABEL", value: "인용", description: "커뮤니티 에디터 인용" },
  { key: "COMMUNITY_EDITOR_BULLET_LIST_LABEL", value: "글머리", description: "커뮤니티 에디터 글머리" },
  { key: "COMMUNITY_EDITOR_BULLET_LIST_TITLE", value: "글머리 목록", description: "커뮤니티 에디터 글머리 목록" },
  { key: "COMMUNITY_EDITOR_ORDERED_LIST_LABEL", value: "번호", description: "커뮤니티 에디터 번호 목록" },
  { key: "COMMUNITY_EDITOR_ORDERED_LIST_TITLE", value: "번호 목록", description: "커뮤니티 에디터 번호 목록 제목" },
  { key: "COMMUNITY_EDITOR_HARD_BREAK_LABEL", value: "줄바꿈", description: "커뮤니티 에디터 줄바꿈" },
  { key: "COMMUNITY_EDITOR_DIVIDER_LABEL", value: "구분선", description: "커뮤니티 에디터 구분선" },
  { key: "COMMUNITY_EDITOR_UNDO_TITLE", value: "실행취소", description: "커뮤니티 에디터 실행취소" },
  { key: "COMMUNITY_EDITOR_REDO_TITLE", value: "다시실행", description: "커뮤니티 에디터 다시실행" },
  { key: "COMMUNITY_COMMENT_LIKE_LABEL", value: "댓글 좋아요", description: "커뮤니티 댓글 좋아요 버튼" },
  { key: "COMMUNITY_COMMENT_UNLIKE_LABEL", value: "댓글 좋아요 취소", description: "커뮤니티 댓글 좋아요 취소 버튼" },
  { key: "COMMUNITY_REPLY_TOGGLE_BUTTON", value: "댓글 달기", description: "커뮤니티 대댓글 열기 버튼" },
  { key: "COMMUNITY_REPLY_SUBMIT_BUTTON", value: "대댓글 등록", description: "커뮤니티 대댓글 등록 버튼" },
  { key: "PROFILE_NOT_FOUND_TITLE", value: "조회할 프로필이 없습니다.", description: "프로필 없음 제목" },
  { key: "PROFILE_NOT_FOUND_DESC", value: "로그인 후 내 프로필을 열거나 Handle 경로로 접근해 주세요.", description: "프로필 없음 안내" },
  { key: "PROFILE_LOADING_LABEL", value: "프로필 로딩 중", description: "프로필 로딩 상태" },
  { key: "PROFILE_LOGIN_REQUIRED_TITLE", value: "내 프로필을 보려면 로그인이 필요합니다.", description: "프로필 로그인 필요 제목" },
  { key: "PROFILE_LOGIN_REQUIRED_DESC", value: "로그인 후 프로필과 활동 기록을 다시 확인해 주세요.", description: "프로필 로그인 필요 안내" },
  { key: "PROFILE_LOGIN_RETURN_MESSAGE", value: "로그인 후 내 프로필 화면으로 돌아옵니다.", description: "프로필 로그인 복귀 안내" },
  { key: "PROFILE_LOAD_FAIL_TITLE", value: "프로필을 불러오지 못했습니다.", description: "프로필 오류 제목" },
  { key: "PROFILE_LOAD_FAIL_DESC", value: "일시적인 오류일 수 있습니다. 잠시 후 다시 시도해 주세요.", description: "프로필 오류 안내" },
  { key: "PROFILE_NOT_FOUND_PAGE_TITLE", value: "존재하지 않는 프로필입니다.", description: "프로필 없음 페이지 제목" },
  { key: "PROFILE_NOT_FOUND_PAGE_DESC", value: "잘못된 Handle이거나 삭제된 사용자입니다. 다른 프로필이나 대시보드에서 다시 이동해 주세요.", description: "프로필 없음 페이지 안내" },
  { key: "PROFILE_RETRY_BUTTON", value: "다시 시도", description: "프로필 다시 시도 버튼" },
  { key: "PROFILE_DASHBOARD_MOVE_BUTTON", value: "대시보드로 이동", description: "프로필 대시보드 이동" },
  { key: "PROFILE_HANDLE_TABLIST_LABEL", value: "프로필 Handle", description: "프로필 Handle 영역" },
  { key: "PROFILE_ALARM_TAB_LABEL", value: "알림 목록", description: "프로필 알림 탭" },
  { key: "PROFILE_EDIT_TAB_LABEL", value: "프로필 수정", description: "프로필 수정 탭" },
  { key: "PROFILE_DELETE_ACCOUNT_BUTTON", value: "회원탈퇴", description: "프로필 회원탈퇴 버튼" },
  { key: "PROFILE_DELETE_DIALOG_TITLE", value: "회원탈퇴", description: "프로필 회원탈퇴 팝업 제목" },
  { key: "PROFILE_DELETE_WARNING_MESSAGE", value: "회원 탈퇴 시 계정 복구는 불가능합니다.", description: "프로필 회원탈퇴 경고" },
  { key: "PROFILE_DELETE_FAIL_MESSAGE", value: "회원탈퇴 처리에 실패했습니다.", description: "프로필 회원탈퇴 실패" },
  { key: "PROFILE_LINK_BLOG_LABEL", value: "Blog", description: "프로필 Blog 링크" },
  { key: "PROFILE_LINK_EMAIL_LABEL", value: "Email", description: "프로필 Email 링크" },
  { key: "PROFILE_LINK_GITHUB_LABEL", value: "GitHub", description: "프로필 GitHub 링크" },
  { key: "PROFILE_SAVE_BIO_SUCCESS_TOAST", value: "소개 저장 완료.", description: "프로필 소개 저장 완료" },
  { key: "PROFILE_SAVE_CARD_SUCCESS_TOAST", value: "프로필 카드 저장 완료.", description: "프로필 카드 저장 완료" },
  { key: "PROFILE_SAVE_LINKS_SUCCESS_TOAST", value: "링크 저장 완료.", description: "프로필 링크 저장 완료" },
  { key: "PROFILE_SAVE_DEFAULT_DBMS_SUCCESS_TOAST", value: "기본 DBMS 저장 완료.", description: "프로필 기본 DBMS 저장 완료" },
  { key: "PROFILE_SAVE_SQL_VISIBILITY_SUCCESS_TOAST", value: "SQL 공개 설정 저장 완료.", description: "프로필 SQL 공개 저장 완료" },
  { key: "PROFILE_SAVE_ACTIVITY_VISIBILITY_SUCCESS_TOAST", value: "커뮤니티 활동 공개 설정 저장 완료.", description: "프로필 활동 공개 저장 완료" },
  { key: "PROFILE_IMAGE_LOAD_FAIL_MESSAGE", value: "이미지 파일을 불러오지 못했습니다.", description: "프로필 이미지 로드 오류" },
  { key: "PROFILE_IMAGE_TYPE_FAIL_MESSAGE", value: "사진 파일만 업로드할 수 있습니다.", description: "프로필 이미지 형식 오류" },
  { key: "PROFILE_IMAGE_EDIT_FAIL_MESSAGE", value: "이미지 편집에 실패했습니다.", description: "프로필 이미지 편집 오류" },
  { key: "PROFILE_AVATAR_UPLOAD_SUCCESS_TOAST", value: "프로필 사진 업로드 완료.", description: "프로필 사진 업로드 완료" },
  { key: "PROFILE_BACKGROUND_UPLOAD_SUCCESS_TOAST", value: "프로필 배경 업로드 완료.", description: "프로필 배경 업로드 완료" },
  { key: "PROFILE_AVATAR_UPLOAD_FAIL_MESSAGE", value: "프로필 사진 업로드에 실패했습니다.", description: "프로필 사진 업로드 오류" },
  { key: "PROFILE_BACKGROUND_UPLOAD_FAIL_MESSAGE", value: "프로필 배경 업로드에 실패했습니다.", description: "프로필 배경 업로드 오류" },
  { key: "PROFILE_SAVE_FAIL_MESSAGE", value: "프로필을 저장하지 못했습니다.", description: "프로필 저장 오류" },
  { key: "PROFILE_ACTIVITY_TAB_POSTS_LABEL", value: "작성한 글", description: "프로필 활동 작성한 글 탭" },
  { key: "PROFILE_ACTIVITY_TAB_COMMENTS_LABEL", value: "작성한 댓글", description: "프로필 활동 작성한 댓글 탭" },
  { key: "PROFILE_ACTIVITY_TAB_LIKES_LABEL", value: "좋아요한 글", description: "프로필 활동 좋아요한 글 탭" },
  { key: "PROFILE_ACTIVITY_BACK_BUTTON", value: "뒤로가기", description: "프로필 활동 뒤로가기" },
  { key: "PROFILE_ACTIVITY_BADGE", value: "활동", description: "프로필 활동 배지" },
  { key: "PROFILE_ACTIVITY_TITLE", value: "커뮤니티 활동", description: "프로필 활동 제목" },
  { key: "PROFILE_ACTIVITY_DESC", value: "작성한 글, 댓글, 좋아요한 글을 한곳에서 볼 수 있습니다.", description: "프로필 활동 설명" },
  { key: "PROFILE_ACTIVITY_EMPTY_POSTS", value: "아직 작성한 글이 없습니다.", description: "프로필 활동 글 빈 상태" },
  { key: "PROFILE_ACTIVITY_EMPTY_COMMENTS", value: "아직 작성한 댓글이 없습니다.", description: "프로필 활동 댓글 빈 상태" },
  { key: "PROFILE_ACTIVITY_EMPTY_LIKES", value: "좋아요한 글이 아직 없습니다.", description: "프로필 활동 좋아요 빈 상태" },
  { key: "PROFILE_REPLY_LABEL", value: "대댓글", description: "프로필 활동 대댓글 표시" },
  { key: "PROFILE_COMMENT_LABEL", value: "댓글", description: "프로필 활동 댓글 표시" },
  { key: "PROFILE_PROBLEM_SUMMARY_TITLE", value: "문제 풀이 현황", description: "프로필 문제 풀이 제목" },
  { key: "PROFILE_PROBLEM_SUMMARY_ARIA_LABEL", value: "문제 풀이 요약", description: "프로필 문제 풀이 요약" },
  { key: "PROFILE_ATTEMPTED_PROBLEMS_LABEL", value: "시도한 문제", description: "프로필 시도한 문제 수" },
  { key: "PROFILE_ITEM_COUNT_LABEL", value: "{count}개", description: "프로필 개수 표시" },
  { key: "PROFILE_ATTEMPTED_EMPTY_STATE", value: "시도한 문제 없음", description: "프로필 시도한 문제 빈 상태" },
  { key: "PROFILE_PROFILE_SECTION_TITLE", value: "프로필", description: "프로필 카드 제목" },
  { key: "PROFILE_PUBLIC_SOLVED_EMPTY_STATE", value: "공개된 문제 풀이 정보가 없습니다.", description: "프로필 문제 풀이 비공개 상태" },
  { key: "PROFILE_COMMUNITY_ACTIVITY_SECTION_TITLE", value: "커뮤니티 활동", description: "프로필 커뮤니티 활동 제목" },
  { key: "PROFILE_PUBLIC_ACTIVITY_EMPTY_STATE", value: "공개된 커뮤니티 활동이 없습니다.", description: "프로필 커뮤니티 활동 비공개 상태" },
  { key: "PROFILE_ACTIVITY_EMPTY_STATE", value: "활동 없음", description: "프로필 활동 빈 상태" },
  { key: "PROFILE_ALARM_EMPTY_STATE", value: "표시할 알림이 없습니다.", description: "프로필 알림 빈 상태" },
  { key: "PROFILE_ALARM_TABLE_LABEL", value: "프로필 알림 목록", description: "프로필 알림 테이블" },
  { key: "PROFILE_ALARM_PAGE_LABEL", value: "알림 목록 페이지", description: "프로필 알림 페이지" },
  { key: "PROFILE_ALARM_PAGE_INPUT_LABEL", value: "알림 목록 페이지 번호", description: "프로필 알림 페이지 입력" },
  { key: "PROFILE_ALARM_CONTENT_COLUMN_LABEL", value: "알림 내용", description: "프로필 알림 내용 헤더" },
  { key: "PROFILE_COMMUNITY_ACTIVITY_TABLE_LABEL", value: "프로필 커뮤니티 활동", description: "프로필 커뮤니티 활동 테이블" },
  { key: "PROFILE_COMMUNITY_ACTIVITY_PAGE_LABEL", value: "커뮤니티 활동 페이지", description: "프로필 커뮤니티 활동 페이지" },
  { key: "PROFILE_COMMUNITY_ACTIVITY_PAGE_INPUT_LABEL", value: "커뮤니티 활동 페이지 번호", description: "프로필 커뮤니티 활동 페이지 입력" },
  { key: "PROFILE_COMMUNITY_ACTIVITY_POST_MESSAGE_PREFIX", value: "커뮤니티에", description: "프로필 커뮤니티 글 앞문장" },
  { key: "PROFILE_COMMUNITY_ACTIVITY_POST_MESSAGE_SUFFIX", value: "을 작성했습니다.", description: "프로필 커뮤니티 글 뒷문장" },
  { key: "PROFILE_COMMUNITY_ACTIVITY_LIKE_POST_MIDDLE", value: "에", description: "프로필 커뮤니티 글 좋아요 연결" },
  { key: "PROFILE_COMMUNITY_ACTIVITY_LIKE_POST_END", value: "를 남겼습니다.", description: "프로필 커뮤니티 글 좋아요 끝문장" },
  { key: "PROFILE_COMMUNITY_ACTIVITY_COMMENT_MIDDLE", value: "에", description: "프로필 커뮤니티 댓글 연결" },
  { key: "PROFILE_COMMUNITY_ACTIVITY_COMMENT_SUFFIX", value: "을 남겼습니다.", description: "프로필 커뮤니티 댓글 끝문장" },
  { key: "PROFILE_COMMUNITY_ACTIVITY_LIKED_COMMENT_MIDDLE", value: "의", description: "프로필 좋아요한 댓글 연결" },
  { key: "PROFILE_COMMUNITY_ACTIVITY_LIKED_COMMENT_AFTER_COMMENT", value: "에", description: "프로필 좋아요한 댓글 뒤 연결" },
  { key: "PROFILE_COMMUNITY_ACTIVITY_LIKED_COMMENT_END", value: "를 남겼습니다.", description: "프로필 좋아요한 댓글 끝문장" },
  { key: "PROFILE_COMMENT_MOVE_LABEL", value: "댓글로 이동", description: "프로필 댓글 이동" },
  { key: "PROFILE_CARD_SECTION_LABEL", value: "프로필 카드", description: "프로필 카드 섹션" },
  { key: "PROFILE_BIO_SECTION_LABEL", value: "소개", description: "프로필 소개 섹션" },
  { key: "PROFILE_LINKS_SECTION_LABEL", value: "링크", description: "프로필 링크 섹션" },
  { key: "PROFILE_EXTERNAL_LINKS_LABEL", value: "외부 링크", description: "프로필 외부 링크" },
  { key: "PROFILE_LINKS_EMPTY_STATE", value: "등록된 링크 없음", description: "프로필 링크 빈 상태" },
  { key: "PROFILE_LINK_LABEL_FIELD", value: "키 (Label)", description: "프로필 링크 키 헤더" },
  { key: "PROFILE_LINK_VALUE_FIELD", value: "URL", description: "프로필 링크 URL 헤더" },
  { key: "PROFILE_LINK_LABEL_PLACEHOLDER", value: "Blog", description: "프로필 링크 라벨 입력" },
  { key: "PROFILE_LINK_URL_PLACEHOLDER", value: "https://", description: "프로필 링크 URL 입력" },
  { key: "PROFILE_DEFAULT_DBMS_LABEL", value: "기본 DBMS", description: "프로필 기본 DBMS 라벨" },
  { key: "PROFILE_DEFAULT_DBMS_SELECT_LABEL", value: "기본 DBMS 선택", description: "프로필 기본 DBMS 선택" },
  { key: "PROFILE_SQL_VISIBILITY_LABEL", value: "작성한 SQL 공개 여부", description: "프로필 SQL 공개 라벨" },
  { key: "PROFILE_COMMUNITY_VISIBILITY_LABEL", value: "커뮤니티 활동 공개 여부", description: "프로필 활동 공개 라벨" },
  { key: "PROFILE_HEATMAP_LAYOUT_LABEL", value: "프로필 활동 캘린더", description: "프로필 활동 캘린더" },
  { key: "PROFILE_HEATMAP_YEAR_TABLIST_LABEL", value: "활동 캘린더 연도 선택", description: "프로필 활동 캘린더 연도" },
  { key: "PROFILE_HEATMAP_SUBMISSION_COUNT_LABEL", value: "문제 제출 {count}건", description: "프로필 제출 수" },
  { key: "PROFILE_HEATMAP_COMMUNITY_COUNT_LABEL", value: "커뮤니티 활동 {count}건", description: "프로필 커뮤니티 수" },
  { key: "PROFILE_IMAGE_CROP_BACKGROUND_TITLE", value: "프로필 배경 자르기", description: "프로필 배경 자르기 제목" },
  { key: "PROFILE_IMAGE_CROP_AVATAR_TITLE", value: "프로필 사진 자르기", description: "프로필 사진 자르기 제목" },
  { key: "AUTH_EMAIL_HINT", value: "올바른 이메일 형식으로 입력해 주세요.", description: "회원 인증 이메일 안내" },
  { key: "AUTH_EMAIL_CHECKING_MESSAGE", value: "이메일 사용 가능 여부를 확인하는 중입니다.", description: "회원 인증 이메일 확인 중" },
  { key: "AUTH_EMAIL_AVAILABLE_MESSAGE", value: "사용 가능한 이메일입니다.", description: "회원 인증 이메일 사용 가능" },
  { key: "AUTH_EMAIL_DUPLICATED_MESSAGE", value: "이미 사용 중인 이메일입니다.", description: "회원 인증 이메일 중복" },
  { key: "AUTH_CODE_HINT", value: "이메일로 받은 인증코드 6자를 입력해 주세요.", description: "회원 인증 코드 안내" },
  { key: "AUTH_CODE_SENT_MESSAGE", value: "인증 코드를 전송했습니다. 5분 이내에 입력해 주세요.", description: "회원 인증 코드 전송 완료" },
  { key: "AUTH_CODE_VERIFIED_MESSAGE", value: "인증 코드가 확인되었습니다. 비밀번호를 입력해 주세요.", description: "회원가입 인증 완료" },
  { key: "AUTH_PASSWORD_HINT", value: "특수문자를 포함해 8자 이상 입력해 주세요.", description: "회원 인증 비밀번호 안내" },
  { key: "AUTH_PASSWORD_CONFIRM_HINT", value: "비밀번호를 다시 입력해 주세요.", description: "회원 인증 비밀번호 확인 안내" },
  { key: "AUTH_RESET_CODE_VERIFIED_MESSAGE", value: "인증 코드가 확인되었습니다. 새 비밀번호를 입력해 주세요.", description: "비밀번호 재설정 인증 완료" },
  { key: "AUTH_RESET_PASSWORD_CHANGED_MESSAGE", value: "비밀번호가 변경되었습니다. 다시 로그인해 주세요.", description: "비밀번호 변경 완료" },
  { key: "AUTH_GOOGLE_LOGIN_FAIL_MESSAGE", value: "Google 로그인에 실패했습니다.", description: "소셜 로그인 Google 오류" },
  { key: "AUTH_GITHUB_LOGIN_FAIL_MESSAGE", value: "Github 로그인에 실패했습니다.", description: "소셜 로그인 Github 오류" },
  { key: "AUTH_KAKAO_LOGIN_FAIL_MESSAGE", value: "Kakao 로그인에 실패했습니다.", description: "소셜 로그인 Kakao 오류" },
  { key: "AUTH_SOCIAL_LOGIN_FAIL_MESSAGE", value: "소셜 로그인에 실패했습니다.", description: "소셜 로그인 공통 오류" },
  { key: "AUTH_POPUP_BLOCKED_MESSAGE", value: "팝업이 차단되어 소셜 로그인을 진행할 수 없습니다.", description: "소셜 로그인 팝업 차단" },
  { key: "AUTH_EMAIL_DUPLICATE_CHECK_FAIL_MESSAGE", value: "이메일 중복 확인 중 오류가 발생했습니다.", description: "회원가입 이메일 확인 오류" },
  { key: "AUTH_LOGIN_FAIL_MESSAGE", value: "로그인에 실패했습니다.", description: "로그인 실패" },
  { key: "AUTH_LOGIN_ERROR_MESSAGE", value: "로그인 중 오류가 발생했습니다.", description: "로그인 처리 오류" },
  { key: "AUTH_CODE_SEND_FAIL_MESSAGE", value: "인증 코드 전송 중 오류가 발생했습니다.", description: "인증 코드 전송 오류" },
  { key: "AUTH_CODE_VERIFY_FAIL_MESSAGE", value: "인증 코드 확인 중 오류가 발생했습니다.", description: "인증 코드 확인 오류" },
  { key: "AUTH_SIGNUP_SESSION_FAIL_MESSAGE", value: "회원가입 후 세션을 확인하지 못했습니다.", description: "회원가입 세션 확인 오류" },
  { key: "AUTH_SIGNUP_ERROR_MESSAGE", value: "회원가입 중 오류가 발생했습니다.", description: "회원가입 처리 오류" },
  { key: "AUTH_PASSWORD_CHANGE_FAIL_MESSAGE", value: "비밀번호 변경 중 오류가 발생했습니다.", description: "비밀번호 변경 오류" },
  { key: "AUTH_SIGNUP_TITLE", value: "이메일로 가입하기", description: "로그인 팝업 가입 제목" },
  { key: "AUTH_RESET_TITLE", value: "비밀번호 찾기", description: "로그인 팝업 비밀번호 찾기 제목" },
  { key: "AUTH_LOGIN_TITLE", value: "로그인", description: "로그인 팝업 제목" },
  { key: "AUTH_LOGIN_EMAIL_PLACEHOLDER", value: "이메일을 입력하세요", description: "로그인 이메일 입력" },
  { key: "AUTH_LOGIN_PASSWORD_PLACEHOLDER", value: "비밀번호를 입력하세요", description: "로그인 비밀번호 입력" },
  { key: "AUTH_LOGIN_IN_PROGRESS_ELLIPSIS", value: "로그인 중…", description: "로그인 버튼 진행 상태" },
  { key: "AUTH_FORGOT_PASSWORD_LINK", value: "비밀번호를 잊으셨나요?", description: "로그인 비밀번호 찾기 링크" },
  { key: "AUTH_CONTINUE_WITH_GOOGLE", value: "Google로 계속하기", description: "소셜 로그인 Google 버튼" },
  { key: "AUTH_CONTINUE_WITH_GITHUB", value: "Github로 계속하기", description: "소셜 로그인 Github 버튼" },
  { key: "AUTH_CONTINUE_WITH_KAKAO", value: "Kakao로 계속하기", description: "소셜 로그인 Kakao 버튼" },
  { key: "AUTH_CONTINUE_WITH_EMAIL", value: "이메일로 계속하기", description: "이메일 로그인 버튼" },
  { key: "AUTH_EMAIL_PLACEHOLDER_POLITE", value: "이메일을 입력해 주세요.", description: "회원가입 이메일 입력" },
  { key: "AUTH_CODE_PLACEHOLDER_POLITE", value: "이메일로 받은 6자리 코드를 입력해 주세요.", description: "회원가입 인증 코드 입력" },
  { key: "AUTH_PASSWORD_PLACEHOLDER_POLITE", value: "비밀번호를 입력해 주세요.", description: "회원가입 비밀번호 입력" },
  { key: "AUTH_EMAIL_LABEL", value: "이메일", description: "회원 인증 이메일 라벨" },
  { key: "AUTH_PASSWORD_LABEL", value: "비밀번호", description: "회원 인증 비밀번호 라벨" },
  { key: "AUTH_CODE_LABEL", value: "인증 코드", description: "회원 인증 코드 라벨" },
  { key: "AUTH_PASSWORD_CONFIRM_LABEL", value: "비밀번호 확인", description: "회원가입 비밀번호 확인 라벨" },
  { key: "AUTH_PASSWORD_CONFIRM_PLACEHOLDER", value: "비밀번호를 다시 입력해 주세요.", description: "회원 인증 비밀번호 확인 입력" },
  { key: "AUTH_CODE_SEND_BUTTON", value: "코드 전송", description: "회원 인증 코드 전송 버튼" },
  { key: "AUTH_CODE_VERIFY_BUTTON", value: "코드 확인", description: "회원 인증 코드 확인 버튼" },
  { key: "AUTH_SIGNUP_PROGRESS_LABEL", value: "가입 중", description: "회원가입 버튼 진행 상태" },
  { key: "AUTH_SIGNUP_BUTTON", value: "가입하기", description: "회원가입 버튼" },
  { key: "AUTH_BACK_TO_LOGIN_BUTTON", value: "로그인으로 돌아가기", description: "회원가입 뒤로가기" },
  { key: "AUTH_RESET_EMAIL_PLACEHOLDER", value: "가입한 이메일을 입력해 주세요.", description: "비밀번호 찾기 이메일 입력" },
  { key: "AUTH_RESET_DESCRIPTION", value: "인증 코드를 확인한 뒤 새 비밀번호를 설정합니다.", description: "비밀번호 찾기 안내" },
  { key: "AUTH_NEW_PASSWORD_LABEL", value: "새 비밀번호", description: "비밀번호 찾기 새 비밀번호 라벨" },
  { key: "AUTH_NEW_PASSWORD_PLACEHOLDER", value: "특수문자를 포함해 8자 이상 입력해 주세요.", description: "비밀번호 찾기 새 비밀번호 입력" },
  { key: "AUTH_NEW_PASSWORD_CONFIRM_LABEL", value: "새 비밀번호 확인", description: "비밀번호 찾기 새 비밀번호 확인" },
  { key: "AUTH_PASSWORD_VALIDATION_MESSAGE", value: "비밀번호는 특수문자를 포함해 8자 이상이어야 합니다.", description: "비밀번호 규칙 안내" },
  { key: "AUTH_PASSWORD_CONFIRM_VALIDATION_MESSAGE", value: "비밀번호 확인은 비밀번호와 동일해야 합니다.", description: "비밀번호 확인 규칙" },
  { key: "AUTH_PASSWORD_CONFIRM_MATCH_MESSAGE", value: "비밀번호 확인은 비밀번호와 동일하게 입력해 주세요.", description: "비밀번호 확인 안내" },
  { key: "AUTH_PASSWORD_CHANGE_BUTTON", value: "비밀번호 변경", description: "비밀번호 변경 버튼" },
  { key: "AUTH_PASSWORD_CHANGING_LABEL", value: "변경 중", description: "비밀번호 변경 진행 상태" },
  { key: "AUTH_LOGIN_MODAL_CLOSE_LABEL", value: "로그인 팝업 닫기", description: "로그인 팝업 닫기" },
  { key: "AUTH_LOGIN_FORM_LABEL", value: "로그인 입력", description: "로그인 입력 영역" },
  { key: "AUTH_ACCOUNT_SUPPORT_LABEL", value: "계정 지원", description: "로그인 계정 지원 영역" },
  { key: "PUBLIC_HOME_SIGNUP_TITLE", value: "회원가입", description: "랜딩 회원가입 제목" },
  { key: "PUBLIC_HOME_SIGNUP_CHECKING_MESSAGE", value: "이메일 중복을 확인하고 있습니다.", description: "랜딩 회원가입 이메일 확인" },
  { key: "PUBLIC_HOME_SIGNUP_CODE_PLACEHOLDER", value: "인증코드 6자를 입력하세요", description: "랜딩 회원가입 코드 입력" },
  { key: "PUBLIC_HOME_SIGNUP_PROGRESS_LABEL", value: "처리 중…", description: "랜딩 회원가입 진행 상태" },
  { key: "PUBLIC_HOME_TITLE_PRIMARY", value: "정답과 성능을 함께 평가하는", description: "랜딩 메인 문구 1" },
  { key: "PUBLIC_HOME_TITLE_SECONDARY", value: "SQL 문제 학습 플랫폼", description: "랜딩 메인 문구 2" },
  { key: "RECOVERY_CODE_HINT", value: "이메일로 받은 인증코드 6자를 5분 내에 입력해 주세요.", description: "비밀번호 찾기 코드 안내" },
  { key: "RECOVERY_PASSWORD_HINT", value: "비밀번호는 특수문자를 포함해 8자 이상이어야 합니다.", description: "비밀번호 찾기 비밀번호 안내" },
  { key: "RECOVERY_PASSWORD_CONFIRM_HINT", value: "비밀번호 확인은 비밀번호와 동일하게 입력해 주세요.", description: "비밀번호 찾기 비밀번호 확인 안내" },
  { key: "RECOVERY_GUIDE_EMAIL", value: "가입할 때 사용한 이메일을 입력하면 인증코드를 보내드립니다.", description: "비밀번호 찾기 단계 안내 1" },
  { key: "RECOVERY_GUIDE_RESET", value: "인증코드 확인이 완료되면 새로운 비밀번호를 바로 설정할 수 있습니다.", description: "비밀번호 찾기 단계 안내 2" },
  { key: "RECOVERY_EMAIL_REQUIRED_MESSAGE", value: "가입할 때 사용한 이메일을 입력해 주세요.", description: "비밀번호 찾기 이메일 검증" },
  { key: "RECOVERY_EMAIL_VALID_MESSAGE", value: "인증코드를 받을 수 있는 이메일입니다.", description: "비밀번호 찾기 이메일 확인 완료" },
  { key: "RECOVERY_UNKNOWN_SEND_FAIL_MESSAGE", value: "인증코드 발송 중 알 수 없는 오류가 발생했습니다.", description: "비밀번호 찾기 코드 발송 오류" },
  { key: "RECOVERY_UNKNOWN_VERIFY_FAIL_MESSAGE", value: "인증코드 확인 중 알 수 없는 오류가 발생했습니다.", description: "비밀번호 찾기 코드 확인 오류" },
  { key: "RECOVERY_RESET_SUCCESS_MESSAGE", value: "비밀번호 변경이 완료되었습니다.", description: "비밀번호 찾기 변경 완료" },
  { key: "RECOVERY_UNKNOWN_RESET_FAIL_MESSAGE", value: "비밀번호 재설정 중 알 수 없는 오류가 발생했습니다.", description: "비밀번호 찾기 재설정 오류" },
  { key: "RECOVERY_CODE_PLACEHOLDER", value: "인증코드 6자를 입력하세요", description: "비밀번호 찾기 코드 입력" },
  { key: "RECOVERY_NEW_PASSWORD_PLACEHOLDER", value: "새 비밀번호를 입력하세요", description: "비밀번호 찾기 새 비밀번호 입력" },
  { key: "RECOVERY_NEW_PASSWORD_CONFIRM_PLACEHOLDER", value: "새 비밀번호를 다시 입력하세요", description: "비밀번호 찾기 새 비밀번호 확인 입력" },
  { key: "HANDLE_HINT_MESSAGE", value: "영문, 숫자, 언더스코어(_)와 하이픈(-)만 사용할 수 있으며 최대 15자까지 입력할 수 있습니다.", description: "Handle 설정 안내" },
  { key: "HANDLE_NOTICE_MESSAGE", value: "Handle은 다른 사용자에게 보이는 이름입니다. 한번 설정하면 변경할 수 없습니다.", description: "Handle 설정 주의" },
  { key: "HANDLE_DUPLICATED_MESSAGE", value: "이미 사용 중인 Handle입니다.", description: "Handle 중복 안내" },
  { key: "HANDLE_SETUP_FAIL_MESSAGE", value: "Handle 설정 중 오류가 발생했습니다.", description: "Handle 설정 오류" },
  { key: "HANDLE_SETUP_TITLE", value: "Handle 설정", description: "Handle 설정 제목" },
  { key: "HANDLE_PLACEHOLDER", value: "사용할 Handle을 입력하세요", description: "Handle 입력 안내" },
  { key: "HANDLE_COMPLETE_BUTTON", value: "Handle 설정 완료", description: "Handle 설정 완료 버튼" },
  { key: "PROBLEM_CREATE_NEW_SET_LABEL", value: "신규 테이블셋", description: "문제 생성 신규 테이블셋" },
  { key: "PROBLEM_CREATE_NEW_PROBLEM_LABEL", value: "신규 문제", description: "문제 생성 신규 문제" },
  { key: "PROBLEM_CREATE_SET_LABEL", value: "테이블셋 {problemSetId}", description: "문제 생성 테이블셋 번호" },
  { key: "PROBLEM_CREATE_PROBLEM_LABEL", value: "문제 {problemId}", description: "문제 생성 문제 번호" },
  { key: "PROBLEM_CREATE_NEW_SET_NUMBER_LABEL", value: "{problemSetId}-신규", description: "문제 생성 신규 문제 번호" },
  { key: "PROBLEM_CREATE_TITLE_LABEL", value: "문제 제목", description: "문제 생성 제목 라벨" },
  { key: "PROBLEM_CREATE_DESCRIPTION_LABEL", value: "설명", description: "문제 생성 설명 라벨" },
  { key: "PROBLEM_CREATE_CONDITION_LABEL", value: "조건", description: "문제 생성 조건 라벨" },
  { key: "PROBLEM_CREATE_OUTPUT_LABEL", value: "출력 설명", description: "문제 생성 출력 설명 라벨" },
  { key: "PROBLEM_CREATE_DDL_LABEL", value: "테이블 정보 DDL", description: "문제 생성 DDL 라벨" },
  { key: "PROBLEM_CREATE_ACTUAL_DATA_LABEL", value: "실제 채점 데이터", description: "문제 생성 실제 채점 데이터 라벨" },
  { key: "PROBLEM_CREATE_SAMPLE_DATA_LABEL", value: "예시 데이터", description: "문제 생성 예시 데이터 라벨" },
  { key: "PROBLEM_CREATE_ANSWER_SQL_LABEL", value: "정답 SQL", description: "문제 생성 정답 SQL 라벨" },
  { key: "PROBLEM_CREATE_OUTPUT_EMPTY_STATE", value: "출력 예시가 아직 없습니다.", description: "문제 생성 출력 예시 빈 상태" },
  { key: "PROBLEM_CREATE_PREVIEW_ROW_COUNT_LABEL", value: "행 {count}개", description: "문제 생성 출력 예시 행 수" },
  { key: "PROBLEM_CREATE_SET_DETAIL_FAIL_MESSAGE", value: "테이블셋 정보를 불러오지 못했습니다.", description: "문제 생성 테이블셋 상세 오류" },
  { key: "PROBLEM_CREATE_PREVIEW_FAIL_MESSAGE", value: "출력 예시를 생성하지 못했습니다.", description: "문제 생성 출력 예시 오류" },
  { key: "PROBLEM_CREATE_SAVE_FAIL_MESSAGE", value: "문제를 저장하지 못했습니다.", description: "문제 생성 저장 오류" },
  { key: "PROBLEM_CREATE_TITLE_PLACEHOLDER", value: "문제 제목", description: "문제 생성 제목 입력" },
  { key: "PROBLEM_CREATE_DESCRIPTION_PLACEHOLDER", value: "설명", description: "문제 생성 설명 입력" },
  { key: "PROBLEM_CREATE_SET_SCOPE_TITLE", value: "테이블 범위", description: "문제 생성 테이블 범위 제목" },
  { key: "PROBLEM_CREATE_ACTUAL_DATA_TITLE", value: "실제 채점 데이터 INSERT", description: "문제 생성 실제 채점 데이터 제목" },
  { key: "PROBLEM_CREATE_ACTUAL_DATA_OPEN_TITLE", value: "채점용 데이터 INSERT - Open", description: "문제 생성 공개 채점 데이터 제목" },
  { key: "PROBLEM_CREATE_ACTUAL_DATA_MYSQL_PLACEHOLDER", value: "MySQL 실제 채점 데이터 INSERT", description: "문제 생성 MySQL 실제 채점 데이터 입력" },
  { key: "PROBLEM_CREATE_ACTUAL_DATA_POSTGRES_PLACEHOLDER", value: "PostgreSQL 실제 채점 데이터 INSERT", description: "문제 생성 PostgreSQL 실제 채점 데이터 입력" },
  { key: "PROBLEM_CREATE_HIDDEN_DATA_LABEL", value: "채점용 데이터 - Hidden", description: "문제 생성 숨김 채점 데이터 라벨" },
  { key: "PROBLEM_CREATE_HIDDEN_DATA_TITLE", value: "채점용 데이터 INSERT - Hidden {index}", description: "문제 생성 숨김 채점 데이터 제목" },
  { key: "PROBLEM_CREATE_HIDDEN_DATA_COMPACT_TITLE", value: "채점용 데이터 INSERT - Hidden", description: "문제 생성 숨김 채점 데이터 고정 제목" },
  { key: "PROBLEM_CREATE_HIDDEN_DATA_PLACEHOLDER", value: "채점용 데이터 - Hidden INSERT", description: "문제 생성 숨김 채점 데이터 입력" },
  { key: "PROBLEM_CREATE_SAMPLE_DATA_TITLE", value: "예시 데이터 INSERT", description: "문제 생성 예시 데이터 제목" },
  { key: "PROBLEM_CREATE_OUTPUT_SAMPLE_TITLE", value: "출력 예시", description: "문제 생성 출력 예시 제목" },
  { key: "PROBLEM_CREATE_ANSWER_SQL_TITLE", value: "정답 SQL", description: "문제 생성 정답 SQL 제목" },
  { key: "PROBLEM_CREATE_COMPLETED_FIELDS_LABEL", value: "필수 항목 {count}/{total} 완료", description: "문제 생성 필수 항목 진행" },
  { key: "PROBLEM_CREATE_MISSING_FIELDS_LABEL", value: "필수 항목 누락: {fields}", description: "문제 생성 누락 항목 안내" },
  { key: "PROBLEM_CREATE_OUTPUT_GENERATING_LABEL", value: "출력 예시 생성 중", description: "문제 생성 출력 예시 생성 중" },
  { key: "PROBLEM_CREATE_OUTPUT_GENERATE_BUTTON", value: "출력 예시 생성", description: "문제 생성 출력 예시 생성 버튼" },
  { key: "PROBLEM_CREATE_SAVING_LABEL", value: "문제 저장 중", description: "문제 생성 저장 중" },
  { key: "PROBLEM_CREATE_CREATE_BUTTON", value: "문제 생성", description: "문제 생성 버튼" },
  { key: "PROBLEM_SOLVE_TAB_SUBMIT_LABEL", value: "제출", description: "문제 상세 제출 탭" },
  { key: "PROBLEM_SOLVE_TAB_MY_SUBMISSIONS_LABEL", value: "내 제출 목록", description: "문제 상세 내 제출 탭" },
  { key: "PROBLEM_SOLVE_TAB_TAGGED_POSTS_LABEL", value: "태그된 게시글", description: "문제 상세 태그된 게시글 탭" },
  { key: "PROBLEM_SOLVE_PANEL_EDITOR_LABEL", value: "에디터", description: "문제 풀이 에디터 패널" },
  { key: "PROBLEM_SOLVE_PANEL_RESULT_LABEL", value: "제출 결과", description: "문제 풀이 결과 패널" },
  { key: "PROBLEM_SOLVE_PANEL_CLOSE_LABEL", value: "{label} 닫기", description: "문제 풀이 패널 닫기" },
  { key: "PROBLEM_SOLVE_TABLIST_LABEL", value: "문제 상세 화면 탭 선택", description: "문제 풀이 탭 선택" },
  { key: "PROBLEM_SOLVE_PROBLEM_NUMBER_LABEL", value: "문제 {problemId}", description: "문제 풀이 문제 번호" },
  { key: "PROBLEM_SOLVE_LOGIN_SQL_KEEP_DESC", value: "작성 중인 SQL은 유지됩니다. 로그인 후 이어서 작성할 수 있습니다.", description: "문제 풀이 로그인 안내" },
  { key: "PROBLEM_SOLVE_SIGNUP_SQL_KEEP_DESC", value: "작성 중인 SQL은 유지됩니다. 가입 후 이어서 작성할 수 있습니다.", description: "문제 풀이 가입 안내" },
  { key: "PROBLEM_SOLVE_RESET_DESC", value: "인증 코드를 확인한 뒤 새 비밀번호를 설정합니다.", description: "문제 풀이 비밀번호 찾기 안내" },
  { key: "PROBLEM_SOLVE_EDITOR_FILE_NAME", value: "main.sql", description: "문제 풀이 에디터 파일명" },
  { key: "PROBLEM_SOLVE_EDITOR_OPACITY_LABEL", value: "에디터 투명도 조절", description: "문제 풀이 에디터 투명도" },
  { key: "PROBLEM_SOLVE_EDITOR_FONT_SIZE_LABEL", value: "에디터 글씨 크기 조절", description: "문제 풀이 에디터 글씨 크기" },
  { key: "PROBLEM_SOLVE_SELECT_ONLY_SUBMIT_LABEL", value: "기준 SELECT만 제출", description: "문제 풀이 SELECT 제출 옵션" },
  { key: "PROBLEM_SOLVE_WITH_DDL_SUBMIT_LABEL", value: "위 DDL 포함 제출", description: "문제 풀이 DDL 포함 제출 옵션" },
  { key: "PROBLEM_SOLVE_CURRENT_STATEMENT_RUN_LABEL", value: "현재 구문 실행", description: "문제 풀이 현재 구문 실행" },
  { key: "PROBLEM_SOLVE_NEARBY_STATEMENT_RUN_LABEL", value: "인접 구문 실행", description: "문제 풀이 인접 구문 실행" },
  { key: "PROBLEM_SOLVE_RUN_ALL_LABEL", value: "전체 실행", description: "문제 풀이 전체 실행" },
  { key: "PROBLEM_SOLVE_EXECUTION_PICKER_LABEL", value: "SQL 실행 구문 선택", description: "문제 풀이 실행 구문 선택" },
  { key: "PROBLEM_SOLVE_SUBMIT_PICKER_LABEL", value: "SQL 제출 구문 선택", description: "문제 풀이 제출 구문 선택" },
  { key: "PROBLEM_SOLVE_RESULT_EMPTY_STATE", value: "표시할 실행 결과가 없습니다.", description: "문제 풀이 실행 결과 빈 상태" },
  { key: "PROBLEM_SOLVE_PLAN_EMPTY_STATE", value: "표시할 실행 계획이 없습니다.", description: "문제 풀이 실행 계획 빈 상태" },
  { key: "PROBLEM_SOLVE_RESULT_PAGE_LOADING_LABEL", value: "실행 결과 페이지 로딩 중", description: "문제 풀이 실행 결과 로딩" },
  { key: "PROBLEM_SOLVE_RESULT_COLUMN_FALLBACK", value: "컬럼 {index}", description: "문제 풀이 결과 컬럼 기본값" },
  { key: "PROBLEM_SOLVE_RESULT_PAGE_LABEL", value: "실행 결과 페이지", description: "문제 풀이 실행 결과 페이지" },
  { key: "PROBLEM_SOLVE_RESULT_PAGE_INPUT_LABEL", value: "이동할 페이지 입력", description: "문제 풀이 실행 결과 페이지 입력" },
  { key: "PROBLEM_SOLVE_RESULT_PAGE_INPUT_OPEN_LABEL", value: "이동할 페이지 입력 열기", description: "문제 풀이 실행 결과 페이지 입력 열기" },
  { key: "PROBLEM_SOLVE_RESULT_WIDTH_RESET_LABEL", value: "실행 결과 너비 초기화", description: "문제 풀이 실행 결과 너비 초기화" },
  { key: "PROBLEM_SOLVE_RUNNING_MESSAGE", value: "SQL을 실행하는 중입니다.", description: "문제 풀이 실행 중 상태" },
  { key: "PROBLEM_SOLVE_PENDING_MESSAGE", value: "실행 대기 중", description: "문제 풀이 실행 대기 상태" },
  { key: "PROBLEM_SOLVE_EXECUTION_FAIL_MESSAGE", value: "실행에 실패했습니다.", description: "문제 풀이 실행 오류" },
  { key: "PROBLEM_SOLVE_SUBMIT_RECORD_FAIL_MESSAGE", value: "제출을 기록하지 못했습니다.", description: "문제 풀이 제출 기록 오류" },
  { key: "PROBLEM_SOLVE_MOVE_RESULT_BUTTON", value: "실행 결과 위치로 이동", description: "문제 풀이 실행 결과 이동" },
  { key: "PROBLEM_SOLVE_SUBMIT_NOT_SUPPORTED_MESSAGE", value: "선택한 DBMS로 제출할 수 없습니다.", description: "문제 풀이 제출 제한" },
  { key: "PROBLEM_SOLVE_SUBMIT_SQL_REQUIRED_MESSAGE", value: "제출할 SQL을 입력해 주세요.", description: "문제 풀이 제출 SQL 검증" },
  { key: "PROBLEM_SOLVE_SELECT_REQUIRED_MESSAGE", value: "제출 가능한 SELECT 구문이 없습니다.", description: "문제 풀이 제출 SELECT 검증" },
  { key: "PROBLEM_SOLVE_CONNECTION_FAIL_MESSAGE", value: "문제 실행 연결에 실패했습니다.", description: "문제 풀이 실행 연결 오류" },
  { key: "PROBLEM_SOLVE_SUBMIT_CONNECTION_FAIL_MESSAGE", value: "제출 연결에 실패했습니다.", description: "문제 풀이 제출 연결 오류" },
  { key: "PROBLEM_SOLVE_INTERACTIVE_NOT_SUPPORTED_MESSAGE", value: "선택한 DBMS로 인터랙티브 실행을 시작할 수 없습니다.", description: "문제 풀이 인터랙티브 실행 제한" },
  { key: "PROBLEM_SOLVE_EXECUTE_SQL_REQUIRED_MESSAGE", value: "실행할 SQL을 입력해 주세요.", description: "문제 풀이 실행 SQL 검증" },
  { key: "PROBLEM_SOLVE_STOPPED_MESSAGE", value: "중지됨", description: "문제 풀이 실행 중지 상태" },
  { key: "PROBLEM_SOLVE_STOP_BUTTON", value: "중지", description: "문제 풀이 중지 버튼" },
  { key: "PROBLEM_SOLVE_EXECUTING_LABEL", value: "실행 중", description: "문제 풀이 실행 진행" },
  { key: "PROBLEM_SOLVE_EXECUTE_BUTTON", value: "실행", description: "문제 풀이 실행 버튼" },
  { key: "PROBLEM_SOLVE_EXECUTE_SHORTCUT_LABEL", value: "실행 (Ctrl + Enter)", description: "문제 풀이 실행 버튼" },
  { key: "PROBLEM_SOLVE_SUBMITTING_LABEL", value: "제출 중", description: "문제 풀이 제출 진행" },
  { key: "PROBLEM_SOLVE_SUBMIT_BUTTON", value: "제출", description: "문제 풀이 제출 버튼" },
  { key: "PROBLEM_SOLVE_SUBMIT_SHORTCUT_LABEL", value: "제출 (Ctrl + Shift + Enter)", description: "문제 풀이 제출 버튼" },
  { key: "PROBLEM_SOLVE_SUBMIT_REQUESTING_MESSAGE", value: "제출 요청을 전송하는 중입니다.", description: "문제 풀이 제출 요청 전송 상태" },
  { key: "PROBLEM_SOLVE_EDITOR_PLACEHOLDER", value: "이곳에 SQL을 작성하세요.", description: "문제 풀이 SQL 입력 안내" },
  { key: "PROBLEM_SOLVE_AUTOCOMPLETE_TITLE", value: "SQL 자동완성", description: "문제 풀이 자동완성 제목" },
  { key: "PROBLEM_SOLVE_SUBMIT_RESULT_EMPTY_STATE", value: "제출 결과 없음.", description: "문제 풀이 제출 결과 빈 상태" },
  { key: "PROBLEM_SOLVE_RELATED_PLAN_EMPTY_STATE", value: "감지된 대표 실행계획 요소가 없습니다.", description: "문제 풀이 관련 실행계획 빈 상태" },
  { key: "PROBLEM_SOLVE_RELATED_SUBMIT_EMPTY_STATE", value: "로그인 후 내 제출을 확인할 수 있습니다.", description: "문제 풀이 내 제출 로그인 안내" },
  { key: "PROBLEM_SOLVE_RELATED_PROBLEM_EMPTY_STATE", value: "이 문제에 대한 내 제출이 없습니다.", description: "문제 풀이 내 제출 빈 상태" },
  { key: "PROBLEM_SOLVE_RELATED_COMMUNITY_EMPTY_STATE", value: "이 문제 번호로 태그된 게시글이 없습니다.", description: "문제 풀이 태그된 게시글 빈 상태" },
  { key: "PROBLEM_SOLVE_RELATED_SUBMIT_TABLE_LABEL", value: "내 제출 목록", description: "문제 풀이 내 제출 테이블" },
  { key: "PROBLEM_SOLVE_RELATED_SUBMIT_PAGE_LABEL", value: "내 제출 페이지", description: "문제 풀이 내 제출 페이지" },
  { key: "PROBLEM_SOLVE_RELATED_SUBMIT_PAGE_INPUT_LABEL", value: "이동할 내 제출 페이지 입력", description: "문제 풀이 내 제출 페이지 입력" },
  { key: "PROBLEM_SOLVE_RELATED_SUBMIT_PAGE_INPUT_OPEN_LABEL", value: "이동할 내 제출 페이지 입력 열기", description: "문제 풀이 내 제출 페이지 입력 열기" },
  { key: "PROBLEM_SOLVE_RELATED_TAGGED_POST_TABLE_LABEL", value: "태그된 게시글 목록", description: "문제 풀이 태그된 게시글 테이블" },
  { key: "PROBLEM_SOLVE_RELATED_TAGGED_POST_PAGE_LABEL", value: "태그된 게시글 페이지", description: "문제 풀이 태그된 게시글 페이지" },
  { key: "PROBLEM_SOLVE_RELATED_TAGGED_POST_PAGE_INPUT_LABEL", value: "이동할 태그된 게시글 페이지 입력", description: "문제 풀이 태그된 게시글 페이지 입력" },
  { key: "PROBLEM_SOLVE_RELATED_TAGGED_POST_PAGE_INPUT_OPEN_LABEL", value: "이동할 태그된 게시글 페이지 입력 열기", description: "문제 풀이 태그된 게시글 페이지 입력 열기" },
  { key: "PROBLEM_SOLVE_RELATED_PROBLEM_ID_COLUMN_LABEL", value: "문제 번호", description: "문제 풀이 관련 문제 번호 헤더" },
  { key: "PROBLEM_SOLVE_COMMUNITY_CATEGORY_COLUMN_LABEL", value: "구분", description: "문제 풀이 커뮤니티 구분 헤더" },
  { key: "PROBLEM_SOLVE_LOGIN_REQUIRED_TITLE", value: "문제를 보려면 로그인이 필요합니다.", description: "문제 풀이 로그인 필요 제목" },
  { key: "PROBLEM_SOLVE_LOGIN_REQUIRED_DESC", value: "로그인 후 문제 설명과 제출 화면을 다시 열어 주세요.", description: "문제 풀이 로그인 필요 안내" },
  { key: "PROBLEM_SOLVE_LOGIN_RETURN_MESSAGE", value: "로그인 후 문제 상세 화면으로 돌아옵니다.", description: "문제 풀이 로그인 복귀 안내" },
  { key: "PROBLEM_SOLVE_NOT_FOUND_TITLE", value: "존재하지 않는 문제입니다.", description: "문제 풀이 없음 제목" },
  { key: "PROBLEM_SOLVE_NOT_FOUND_DESC", value: "잘못된 문제 번호이거나 더 이상 제공하지 않는 문제입니다. 문제 목록에서 다시 선택해 주세요.", description: "문제 풀이 없음 안내" },
  { key: "PROBLEM_SOLVE_LOAD_FAIL_TITLE", value: "문제를 불러오지 못했습니다.", description: "문제 풀이 오류 제목" },
  { key: "PROBLEM_SOLVE_LOAD_FAIL_DESC", value: "일시적인 오류일 수 있습니다. 문제 목록에서 다시 시도해 주세요.", description: "문제 풀이 오류 안내" },
  { key: "PROBLEM_DETAIL_COLUMN_NAME_LABEL", value: "컬럼명", description: "문제 상세 컬럼명 헤더" },
  { key: "PROBLEM_DETAIL_COLUMN_DESCRIPTION_LABEL", value: "설명", description: "문제 상세 설명 헤더" },
  { key: "PROBLEM_DETAIL_COLUMN_TYPE_LABEL", value: "타입", description: "문제 상세 타입 헤더" },
  { key: "PROBLEM_DETAIL_COLUMN_KEY_LABEL", value: "키", description: "문제 상세 키 헤더" },
  { key: "PROBLEM_DETAIL_COLUMN_REFERENCE_LABEL", value: "참조", description: "문제 상세 참조 헤더" },
  { key: "PROBLEM_DETAIL_TABLE_SECTION_TITLE", value: "테이블 정보", description: "문제 상세 테이블 정보 제목" },
  { key: "PROBLEM_DETAIL_DRAG_REORDER_TITLE", value: "드래그해 순서 변경", description: "문제 상세 테이블 순서 변경" },
  { key: "PROBLEM_DETAIL_MOVING_STATE", value: "이동 중", description: "문제 상세 드래그 중 상태" },
  { key: "PROBLEM_DETAIL_DROP_HERE_STATE", value: "여기에 놓기", description: "문제 상세 드롭 위치 안내" },
  { key: "PROBLEM_DETAIL_DESCRIPTION_EMPTY_STATE", value: "문제 설명이 없습니다.", description: "문제 상세 설명 빈 상태" },
  { key: "PROBLEM_DETAIL_TABLE_EMPTY_STATE", value: "표시할 테이블 정의가 없습니다.", description: "문제 상세 테이블 빈 상태" },
  { key: "PROBLEM_DETAIL_ERD_SECTION_TITLE", value: "ERD", description: "문제 상세 ERD 제목" },
  { key: "PROBLEM_DETAIL_ERD_EMPTY_STATE", value: "ERD를 만들 DDL이 없습니다.", description: "문제 상세 ERD 빈 상태" },
  { key: "PROBLEM_DETAIL_SAMPLE_SECTION_TITLE", value: "데이터 예시", description: "문제 상세 데이터 예시 제목" },
  { key: "PROBLEM_DETAIL_SAMPLE_EMPTY_STATE", value: "표시할 데이터 예시가 없습니다.", description: "문제 상세 데이터 예시 빈 상태" },
  { key: "PROBLEM_DETAIL_CONDITION_SECTION_TITLE", value: "조건", description: "문제 상세 조건 제목" },
  { key: "PROBLEM_DETAIL_CONDITION_EMPTY_STATE", value: "조건 정보가 없습니다.", description: "문제 상세 조건 빈 상태" },
  { key: "PROBLEM_DETAIL_OUTPUT_SECTION_TITLE", value: "출력", description: "문제 상세 출력 제목" },
  { key: "PROBLEM_DETAIL_OUTPUT_EMPTY_STATE", value: "출력 정보가 없습니다.", description: "문제 상세 출력 빈 상태" },
  { key: "PROBLEM_DETAIL_OUTPUT_SAMPLE_SECTION_TITLE", value: "출력 예시", description: "문제 상세 출력 예시 제목" },
  { key: "PROBLEM_DETAIL_OUTPUT_SAMPLE_EMPTY_STATE", value: "표시할 출력 예시가 없습니다.", description: "문제 상세 출력 예시 빈 상태" },
  { key: "PROBLEM_DETAIL_TABLE_NAME_FALLBACK", value: "{tableName} 테이블", description: "문제 상세 테이블 기본 설명" },
  { key: "PROBLEM_DETAIL_COLUMN_TIME_FALLBACK", value: "{columnName} 시각", description: "문제 상세 시각 컬럼 기본 설명" },
  { key: "PROBLEM_DETAIL_COLUMN_DATE_FALLBACK", value: "{columnName} 날짜", description: "문제 상세 날짜 컬럼 기본 설명" },
  { key: "PROBLEM_DETAIL_COLUMN_AMOUNT_FALLBACK", value: "{columnName} 금액", description: "문제 상세 금액 컬럼 기본 설명" },
  { key: "PROBLEM_DETAIL_SAMPLE_DEFAULT_TITLE", value: "예시 데이터", description: "문제 상세 예시 데이터 기본 제목" },
  { key: "ALARM_READ_FAIL_MESSAGE", value: "알림 읽음 처리에 실패했습니다.", description: "알림 읽음 처리 오류" },
  { key: "ALARM_SEND_RECIPIENT_LOAD_FAIL_MESSAGE", value: "수신자 목록을 불러오지 못했습니다.", description: "알람 전송 수신자 로드 오류" },
  { key: "ALARM_SEND_RECIPIENT_REMOVE_LABEL", value: "{handle} 제거", description: "알람 전송 수신자 제거" },
  { key: "ANOMALY_BLOCK_USER_FAIL_MESSAGE", value: "계정을 차단하지 못했습니다.", description: "이상계정 차단 오류" },
  { key: "ANOMALY_UNBLOCK_IP_FAIL_MESSAGE", value: "IP 차단을 해제하지 못했습니다.", description: "차단 IP 해제 오류" },
  { key: "ANOMALY_UNBLOCK_USER_FAIL_MESSAGE", value: "계정 차단을 해제하지 못했습니다.", description: "차단 계정 해제 오류" },
  { key: "AUTH_BROWSER_ENCRYPTION_UNAVAILABLE_MESSAGE", value: "브라우저 암호화 기능을 사용할 수 없습니다.", description: "인증 브라우저 암호화 오류" },
  { key: "AUTH_LOGIN_PARSE_FAIL_MESSAGE", value: "로그인 응답 형식이 올바르지 않습니다.", description: "로그인 응답 파싱 오류" },
  { key: "AUTH_LOGOUT_FAIL_MESSAGE", value: "로그아웃에 실패했습니다.", description: "로그아웃 오류" },
  { key: "AUTH_SESSION_RESTORE_FAIL_MESSAGE", value: "세션 복원 확인에 실패했습니다.", description: "세션 복원 오류" },
  { key: "COMMUNITY_EDITOR_IMAGE_UPLOAD_PARSE_FAIL_MESSAGE", value: "이미지 업로드 응답 형식이 올바르지 않습니다.", description: "커뮤니티 이미지 업로드 응답 오류" },
  { key: "COMMUNITY_TAG_AUTOCOMPLETE_LOAD_FAIL_MESSAGE", value: "태그 자동완성을 불러오지 못했습니다.", description: "커뮤니티 태그 자동완성 오류" },
  { key: "FAVORITES_LOAD_FAIL_MESSAGE", value: "즐겨찾기를 불러오지 못했습니다.", description: "즐겨찾기 로드 오류" },
  { key: "FAVORITES_PARSE_FAIL_MESSAGE", value: "즐겨찾기 응답 형식이 올바르지 않습니다.", description: "즐겨찾기 응답 오류" },
  { key: "FAVORITES_SAVE_FAIL_MESSAGE", value: "즐겨찾기를 저장하지 못했습니다.", description: "즐겨찾기 저장 오류" },
  { key: "GLOBAL_CONFIG_COLUMN_RESIZE_LABEL", value: "{label} 너비 조절", description: "UI 텍스트 컬럼 너비 조절" },
  { key: "HANDLE_DUPLICATE_CHECK_FAIL_MESSAGE", value: "Handle 중복 확인 중 오류가 발생했습니다.", description: "Handle 중복 확인 오류" },
  { key: "HANDLE_SETUP_PARSE_FAIL_MESSAGE", value: "Handle 설정 응답 형식이 올바르지 않습니다.", description: "Handle 설정 응답 오류" },
  { key: "HEADER_ALARM_DIALOG_LABEL", value: "알림", description: "헤더 알림 팝업 제목" },
  { key: "HEADER_ALARM_LIST_MOVE_LABEL", value: "알림 목록으로 이동", description: "헤더 알림 목록 이동" },
  { key: "HEADER_ALARM_OPEN_LABEL", value: "알림 열기", description: "헤더 알림 열기" },
  { key: "HEADER_ALARM_OPEN_WITH_UNREAD_LABEL", value: "알림 열기 (읽지 않음 {count}개)", description: "헤더 읽지 않은 알림 열기" },
  { key: "HEADER_ALARM_PAGE_INPUT_LABEL", value: "이동할 알림 페이지 입력", description: "헤더 알림 페이지 입력" },
  { key: "HEADER_ALARM_PAGE_INPUT_OPEN_LABEL", value: "이동할 알림 페이지 입력 열기", description: "헤더 알림 페이지 입력 열기" },
  { key: "HEADER_ALARM_PAGE_LABEL", value: "알림 페이지", description: "헤더 알림 페이지" },
  { key: "HEADER_FAVORITES_BUTTON_LABEL", value: "즐겨찾기", description: "헤더 즐겨찾기 버튼" },
  { key: "HEADER_FAVORITES_DIALOG_LABEL", value: "즐겨찾기", description: "헤더 즐겨찾기 팝업 제목" },
  { key: "HEADER_FAVORITES_PAGE_INPUT_LABEL", value: "이동할 즐겨찾기 페이지 입력", description: "헤더 즐겨찾기 페이지 입력" },
  { key: "HEADER_FAVORITES_PAGE_INPUT_OPEN_LABEL", value: "이동할 즐겨찾기 페이지 입력 열기", description: "헤더 즐겨찾기 페이지 입력 열기" },
  { key: "HEADER_FAVORITES_PAGE_LABEL", value: "즐겨찾기 페이지", description: "헤더 즐겨찾기 페이지" },
  { key: "HEADER_MOBILE_CURRENT_LABEL", value: "현재", description: "헤더 모바일 현재 표시" },
  { key: "HEADER_MOBILE_MENU_CLOSE_LABEL", value: "모바일 메뉴 닫기", description: "헤더 모바일 메뉴 닫기" },
  { key: "HEADER_MOBILE_MENU_DIALOG_LABEL", value: "모바일 메뉴", description: "헤더 모바일 메뉴 제목" },
  { key: "HEADER_MOBILE_MENU_OPEN_LABEL", value: "모바일 메뉴 열기", description: "헤더 모바일 메뉴 열기" },
  { key: "HEADER_MOBILE_MENU_TITLE", value: "메뉴", description: "헤더 모바일 메뉴 제목" },
  { key: "HEADER_MOBILE_MOVE_LABEL", value: "이동", description: "헤더 모바일 이동 표시" },
  { key: "HEADER_MOBILE_MY_INFO_LABEL", value: "내 정보", description: "헤더 모바일 내 정보" },
  { key: "HEADER_MOBILE_MY_PAGE_LABEL", value: "내 페이지", description: "헤더 모바일 내 페이지" },
  { key: "HEADER_MOBILE_QUICK_NAV_LABEL", value: "빠른 이동", description: "헤더 모바일 빠른 이동" },
  { key: "HEADER_MOBILE_SAVED_TABS_LABEL", value: "저장된 탭", description: "헤더 모바일 저장된 탭" },
  { key: "HEADER_MOBILE_SESSION_END_LABEL", value: "세션 종료", description: "헤더 모바일 세션 종료" },
  { key: "HEADER_NAV_LABEL", value: "주요 메뉴", description: "헤더 주요 메뉴" },
  { key: "HOME_DBMS_TABLIST_LABEL", value: "문제 목록 DBMS 선택", description: "문제 목록 DBMS 선택" },
  { key: "HOME_FAVORITE_LABEL", value: "문제 / {dbms}", description: "문제 목록 즐겨찾기 라벨" },
  { key: "HOME_PAGE_INPUT_LABEL", value: "이동할 페이지 입력", description: "문제 목록 페이지 입력" },
  { key: "HOME_PAGE_INPUT_OPEN_LABEL", value: "이동할 페이지 입력 열기", description: "문제 목록 페이지 입력 열기" },
  { key: "HOME_PAGE_NAV_LABEL", value: "문제 페이지", description: "문제 목록 페이지" },
  { key: "HOME_PROBLEM_SEARCH_LABEL", value: "문제 검색", description: "문제 목록 검색" },
  { key: "IMAGE_CROP_CANVAS_FAIL_MESSAGE", value: "이미지 편집용 캔버스를 생성할 수 없습니다.", description: "이미지 편집 캔버스 오류" },
  { key: "IMAGE_CROP_CONVERT_FAIL_MESSAGE", value: "이미지를 변환하지 못했습니다.", description: "이미지 변환 오류" },
  { key: "IMAGE_CROP_LOAD_FAIL_MESSAGE", value: "이미지를 불러오지 못했습니다.", description: "이미지 로드 오류" },
  { key: "PROBLEM_DETAIL_PARSE_FAIL_MESSAGE", value: "문제 정보 응답 형식이 올바르지 않습니다.", description: "문제 상세 응답 오류" },
  { key: "PROBLEM_TABLE_COST_SPREAD_FILTER_OPEN_LABEL", value: "Cost 편차 필터 열기", description: "문제 목록 Cost 편차 필터 열기" },
  { key: "PROBLEM_TABLE_COST_SPREAD_FILTER_OPTIONS_LABEL", value: "Cost 편차 필터 옵션", description: "문제 목록 Cost 편차 필터 옵션" },
  { key: "PROBLEM_TABLE_LABEL", value: "문제 목록", description: "문제 목록 테이블 제목" },
  { key: "PROBLEM_TABLE_SOLVED_COUNT_SORT_ASC_LABEL", value: "푼 사람 수 오름차순", description: "문제 목록 푼 사람 수 오름차순" },
  { key: "PROBLEM_TABLE_SOLVED_COUNT_SORT_DESC_LABEL", value: "푼 사람 수 내림차순", description: "문제 목록 푼 사람 수 내림차순" },
  { key: "PROBLEM_TABLE_SOLVE_FILTER_OPEN_LABEL", value: "해결 여부 필터 열기", description: "문제 목록 해결 여부 필터 열기" },
  { key: "PROBLEM_TABLE_SOLVE_FILTER_OPTIONS_LABEL", value: "해결 여부 필터 옵션", description: "문제 목록 해결 여부 필터 옵션" },
  { key: "PROBLEM_TABLE_SUCCESS_SUBMIT_SORT_ASC_LABEL", value: "정답 제출 오름차순", description: "문제 목록 정답 제출 오름차순" },
  { key: "PROBLEM_TABLE_SUCCESS_SUBMIT_SORT_DESC_LABEL", value: "정답 제출 내림차순", description: "문제 목록 정답 제출 내림차순" },
  { key: "PROBLEM_TABLE_TOTAL_SUBMIT_SORT_ASC_LABEL", value: "전체 제출 오름차순", description: "문제 목록 전체 제출 오름차순" },
  { key: "PROBLEM_TABLE_TOTAL_SUBMIT_SORT_DESC_LABEL", value: "전체 제출 내림차순", description: "문제 목록 전체 제출 내림차순" },
  { key: "PROFILE_COMMUNITY_COMMENTS_LOAD_FAIL_MESSAGE", value: "프로필 커뮤니티 댓글을 불러오지 못했습니다.", description: "프로필 커뮤니티 댓글 로드 오류" },
  { key: "PROFILE_COMMUNITY_POSTS_LOAD_FAIL_MESSAGE", value: "프로필 커뮤니티 게시글을 불러오지 못했습니다.", description: "프로필 커뮤니티 게시글 로드 오류" },
  { key: "PROFILE_PARSE_FAIL_MESSAGE", value: "프로필 응답 형식이 올바르지 않습니다.", description: "프로필 응답 오류" },
  { key: "RANKING_COST_PERCENTILE_SORT_ASC_LABEL", value: "평균 Cost 백분위 오름차순 정렬", description: "랭킹 Cost 백분위 오름차순" },
  { key: "RANKING_DBMS_TABLIST_LABEL", value: "랭킹 DBMS 선택", description: "랭킹 DBMS 선택" },
  { key: "RANKING_FAVORITE_LABEL", value: "랭킹 / {dbms}", description: "랭킹 즐겨찾기 라벨" },
  { key: "RANKING_HANDLE_MENU_OPEN_LABEL", value: "{handle} Handle 메뉴 열기", description: "랭킹 Handle 메뉴 열기" },
  { key: "RANKING_HANDLE_SEARCH_LABEL", value: "Handle 검색", description: "랭킹 Handle 검색" },
  { key: "RANKING_HANDLE_SEARCH_PLACEHOLDER", value: "Handle 검색", description: "랭킹 Handle 검색 입력" },
  { key: "RANKING_HANDLE_SEARCH_SUBMIT_LABEL", value: "Handle 검색 실행", description: "랭킹 Handle 검색 실행" },
  { key: "RANKING_PAGE_INPUT_LABEL", value: "이동할 랭킹 페이지 입력", description: "랭킹 페이지 입력" },
  { key: "RANKING_PAGE_INPUT_OPEN_LABEL", value: "이동할 랭킹 페이지 입력 열기", description: "랭킹 페이지 입력 열기" },
  { key: "RANKING_PAGE_LABEL", value: "랭킹 페이지", description: "랭킹 페이지" },
  { key: "RANKING_PROFILE_MOVE_LABEL", value: "{handle} 프로필로 이동", description: "랭킹 프로필 이동" },
  { key: "RANKING_PROFILE_MOVE_MENU_LABEL", value: "{handle} 프로필 이동", description: "랭킹 프로필 이동 메뉴" },
  { key: "RANKING_RANK_COLUMN_LABEL", value: "순위", description: "랭킹 순위 헤더" },
  { key: "RANKING_SOLVED_SORT_DESC_LABEL", value: "해결한 문제 내림차순 정렬", description: "랭킹 해결한 문제 내림차순" },
  { key: "RANKING_TABLE_LABEL", value: "랭킹 목록", description: "랭킹 목록 테이블 제목" },
  { key: "RECOVERY_CODE_SEND_FAIL_MESSAGE", value: "인증 코드 전송 중 오류가 발생했습니다.", description: "비밀번호 찾기 코드 전송 오류" },
  { key: "ADMIN_FAVORITE_LABEL", value: "관리자 / {tab}", description: "관리자 즐겨찾기" },
  { key: "ADMIN_PROBLEM_MANAGE_TAB", value: "문제 관리", description: "관리자 문제 관리" },
  { key: "ADMIN_TABLIST_LABEL", value: "관리자 기능", description: "관리자 탭 목록" },
  { key: "ALARM_TEMPLATE_EDIT_CANCEL_LABEL", value: "{type} 수정 취소", description: "알람 템플릿 라벨" },
  { key: "ALARM_TEMPLATE_EDIT_LABEL", value: "{type} 수정", description: "알람 템플릿 라벨" },
  { key: "ALARM_TEMPLATE_SAVE_LABEL", value: "{type} 저장", description: "알람 템플릿 라벨" },
  { key: "ALARM_TEMPLATE_SENTENCE_COLUMN_LABEL", value: "sentence", description: "알람 템플릿 컬럼" },
  { key: "ANOMALY_BLOCKED_IPS_PAGE_INPUT_LABEL", value: "차단 IP 목록 페이지 번호", description: "이상계정 페이지 입력" },
  { key: "ANOMALY_BLOCKED_IPS_PAGE_LABEL", value: "차단 IP 목록 페이지", description: "이상계정 페이지" },
  { key: "ANOMALY_BLOCKED_IPS_TABLE_LABEL", value: "차단 IP 목록", description: "이상계정 테이블" },
  { key: "ANOMALY_BLOCKED_USERS_PAGE_INPUT_LABEL", value: "차단 계정 목록 페이지 번호", description: "이상계정 페이지 입력" },
  { key: "ANOMALY_BLOCKED_USERS_PAGE_LABEL", value: "차단 계정 목록 페이지", description: "이상계정 페이지" },
  { key: "ANOMALY_BLOCKED_USERS_TABLE_LABEL", value: "차단 계정 목록", description: "이상계정 테이블" },
  { key: "ANOMALY_RANGE_END_INPUT_LABEL", value: "조회 종료 일시", description: "이상계정 라벨" },
  { key: "ANOMALY_RANGE_INPUT_PLACEHOLDER", value: "YYYY-MM-DD HH24:Mi", description: "이상계정 YYYY-MM-DD HH24:Mi" },
  { key: "ANOMALY_RANGE_START_INPUT_LABEL", value: "조회 시작 일시", description: "이상계정 라벨" },
  { key: "ANOMALY_RANGE_TABLIST_LABEL", value: "이상계정 조회 범위", description: "이상계정 탭 목록" },
  { key: "ANOMALY_SECTION_NAV_LABEL", value: "이상계정 감지 섹션", description: "이상계정 라벨" },
  { key: "ANOMALY_TREND_PAGE_INPUT_LABEL", value: "이상계정 추이 페이지 번호", description: "이상계정 페이지 입력" },
  { key: "ANOMALY_TREND_PAGE_LABEL", value: "이상계정 추이 페이지", description: "이상계정 페이지" },
  { key: "ANOMALY_TREND_TABLE_LABEL", value: "이상계정 추이 목록", description: "이상계정 테이블" },
  { key: "AUTH_MANAGE_PAGE_INPUT_LABEL", value: "이동할 권한 설정 페이지 입력", description: "권한 설정 페이지 입력" },
  { key: "AUTH_MANAGE_PAGE_INPUT_OPEN_LABEL", value: "이동할 권한 설정 페이지 입력 열기", description: "권한 설정 페이지 입력 열기" },
  { key: "AUTH_MANAGE_PAGE_LABEL", value: "권한 설정 페이지", description: "권한 설정 페이지" },
  { key: "AUTH_MANAGE_ROLE_EDIT_LABEL", value: "역할 수정", description: "권한 설정 라벨" },
  { key: "AUTH_MANAGE_ROLE_MENU_LABEL", value: "{handle} 역할 선택", description: "권한 설정 라벨" },
  { key: "AUTH_MANAGE_SECTION_NAV_LABEL", value: "권한 설정 섹션", description: "권한 설정 라벨" },
  { key: "AUTH_MANAGE_TABLE_LABEL", value: "권한 설정", description: "권한 설정 테이블" },
  { key: "COMMON_COLUMN_RESIZE_LABEL", value: "{label} 너비 조절", description: "공통 라벨" },
  { key: "COMMON_COMING_SOON_LABEL", value: "예정", description: "공통 라벨" },
  { key: "COMMON_IP_LABEL", value: "IP", description: "공통 라벨" },
  { key: "COMMON_LAYOUT_RESET_LABEL", value: "테이블 정보 레이아웃 초기화", description: "공통 라벨" },
  { key: "COMMON_PREPARING_LABEL", value: "준비 중", description: "공통 라벨" },
  { key: "COMMUNITY_CATEGORY_SELECT_LABEL", value: "게시글 구분 선택", description: "커뮤니티 라벨" },
  { key: "COMMUNITY_COMMENTS_SORT_ASC_LABEL", value: "댓글 수 오름차순 정렬", description: "커뮤니티 오름차순 정렬" },
  { key: "COMMUNITY_COMMENTS_SORT_DEFAULT_LABEL", value: "댓글 수 기본 정렬", description: "커뮤니티 기본 정렬" },
  { key: "COMMUNITY_COMMENTS_SORT_DESC_LABEL", value: "댓글 수 내림차순 정렬", description: "커뮤니티 내림차순 정렬" },
  { key: "COMMUNITY_COMMENT_COUNT_LABEL", value: "댓글 {count}", description: "커뮤니티 개수" },
  { key: "COMMUNITY_COPY_LINK_LABEL", value: "링크 복사", description: "커뮤니티 라벨" },
  { key: "COMMUNITY_DATE_SORT_ASC_LABEL", value: "작성일 오름차순 정렬", description: "커뮤니티 오름차순 정렬" },
  { key: "COMMUNITY_DATE_SORT_DEFAULT_LABEL", value: "작성일 기본 정렬", description: "커뮤니티 기본 정렬" },
  { key: "COMMUNITY_DATE_SORT_DESC_LABEL", value: "작성일 내림차순 정렬", description: "커뮤니티 내림차순 정렬" },
  { key: "COMMUNITY_DETAIL_LOAD_FAIL_DESC", value: "일시적인 오류일 수 있습니다. 커뮤니티 목록에서 다시 시도해 주세요.", description: "커뮤니티 상세 안내" },
  { key: "COMMUNITY_DETAIL_LOAD_FAIL_TITLE", value: "게시글을 불러오지 못했습니다.", description: "커뮤니티 상세 제목" },
  { key: "COMMUNITY_DETAIL_LOGIN_REQUIRED_DESC", value: "로그인 후 게시글 본문과 댓글을 다시 확인해 주세요.", description: "커뮤니티 상세 안내" },
  { key: "COMMUNITY_DETAIL_LOGIN_REQUIRED_TITLE", value: "게시글을 보려면 로그인이 필요합니다.", description: "커뮤니티 상세 제목" },
  { key: "COMMUNITY_DETAIL_LOGIN_RETURN_MESSAGE", value: "로그인 후 이 게시글 화면으로 돌아옵니다.", description: "커뮤니티 상세 메시지" },
  { key: "COMMUNITY_DETAIL_NOT_FOUND_DESC", value: "삭제되었거나 잘못된 주소입니다. 커뮤니티 목록에서 다시 이동해 주세요.", description: "커뮤니티 상세 안내" },
  { key: "COMMUNITY_DETAIL_NOT_FOUND_TITLE", value: "존재하지 않는 게시글입니다.", description: "커뮤니티 상세 제목" },
  { key: "COMMUNITY_EDITOR_BLOCK_GROUP_LABEL", value: "블록", description: "커뮤니티 에디터 라벨" },
  { key: "COMMUNITY_EDITOR_CODE_GROUP_LABEL", value: "코드", description: "커뮤니티 에디터 라벨" },
  { key: "COMMUNITY_EDITOR_HISTORY_GROUP_LABEL", value: "히스토리", description: "커뮤니티 에디터 라벨" },
  { key: "COMMUNITY_EDITOR_INSERT_GROUP_LABEL", value: "삽입", description: "커뮤니티 에디터 라벨" },
  { key: "COMMUNITY_EDITOR_LIST_GROUP_LABEL", value: "목록", description: "커뮤니티 에디터 라벨" },
  { key: "COMMUNITY_EDITOR_TEXT_FORMAT_GROUP_LABEL", value: "텍스트 서식", description: "커뮤니티 에디터 라벨" },
  { key: "COMMUNITY_EDIT_CANCEL_LABEL", value: "수정 취소", description: "커뮤니티 라벨" },
  { key: "COMMUNITY_EMPTY_GUIDE_MESSAGE", value: "검색어를 바꾸거나 필터를 해제해서 다시 찾아보세요.", description: "커뮤니티 메시지" },
  { key: "COMMUNITY_FAVORITE_LABEL", value: "커뮤니티 / {tab}", description: "커뮤니티 즐겨찾기" },
  { key: "COMMUNITY_FAVORITE_POST_LABEL", value: "커뮤니티 / {postId}", description: "커뮤니티 라벨" },
  { key: "COMMUNITY_LIKES_SORT_ASC_LABEL", value: "좋아요 오름차순 정렬", description: "커뮤니티 오름차순 정렬" },
  { key: "COMMUNITY_LIKES_SORT_DEFAULT_LABEL", value: "좋아요 기본 정렬", description: "커뮤니티 기본 정렬" },
  { key: "COMMUNITY_LIKES_SORT_DESC_LABEL", value: "좋아요 내림차순 정렬", description: "커뮤니티 내림차순 정렬" },
  { key: "COMMUNITY_LIKE_BUTTON_LABEL", value: "좋아요", description: "커뮤니티 버튼" },
  { key: "COMMUNITY_LIST_ACTION_LABEL", value: "커뮤니티 목록", description: "커뮤니티 라벨" },
  { key: "COMMUNITY_PAGE_INPUT_LABEL", value: "이동할 커뮤니티 페이지 입력", description: "커뮤니티 페이지 입력" },
  { key: "COMMUNITY_PAGE_INPUT_OPEN_LABEL", value: "이동할 커뮤니티 페이지 입력 열기", description: "커뮤니티 페이지 입력 열기" },
  { key: "COMMUNITY_PAGE_LABEL", value: "커뮤니티 페이지", description: "커뮤니티 페이지" },
  { key: "COMMUNITY_SEARCH_LABEL", value: "커뮤니티 검색", description: "커뮤니티 라벨" },
  { key: "COMMUNITY_SEARCH_RESET_BUTTON", value: "검색 초기화", description: "커뮤니티 버튼" },
  { key: "COMMUNITY_SEARCH_SUBMIT_LABEL", value: "커뮤니티 검색 실행", description: "커뮤니티 라벨" },
  { key: "COMMUNITY_TABLE_LABEL", value: "커뮤니티 목록", description: "커뮤니티 테이블" },
  { key: "COMMUNITY_TABLE_LOADING_LABEL", value: "로딩 중", description: "커뮤니티 라벨" },
  { key: "COMMUNITY_TABLIST_LABEL", value: "커뮤니티 구분 선택", description: "커뮤니티 탭 목록" },
  { key: "COMMUNITY_UNLIKE_BUTTON_LABEL", value: "좋아요 취소", description: "커뮤니티 버튼" },
  { key: "COMMUNITY_UPLOADING_BUTTON", value: "업로드 중", description: "커뮤니티 버튼" },
  { key: "COMMUNITY_VIEWS_SORT_ASC_LABEL", value: "조회수 오름차순 정렬", description: "커뮤니티 오름차순 정렬" },
  { key: "COMMUNITY_VIEWS_SORT_DEFAULT_LABEL", value: "조회수 기본 정렬", description: "커뮤니티 기본 정렬" },
  { key: "COMMUNITY_VIEWS_SORT_DESC_LABEL", value: "조회수 내림차순 정렬", description: "커뮤니티 내림차순 정렬" },
  { key: "COMMUNITY_VIEW_COUNT_LABEL", value: "조회수 {count}", description: "커뮤니티 개수" },
  { key: "COMMUNITY_WRITE_LOGIN_DRAFT_MESSAGE", value: "작성 중인 게시글은 유지됩니다. 로그인 후 이어서 작성할 수 있습니다.", description: "커뮤니티 메시지" },
  { key: "DASHBOARD_COMMUNITY_NEXT_BUTTON_LABEL", value: "다음 커뮤니티 글 보기", description: "대시보드 버튼" },
  { key: "DASHBOARD_COMMUNITY_PAGE_LABEL", value: "커뮤니티 페이지 선택", description: "대시보드 페이지" },
  { key: "DASHBOARD_COMMUNITY_PREVIOUS_BUTTON_LABEL", value: "이전 커뮤니티 글 보기", description: "대시보드 버튼" },
  { key: "DASHBOARD_COMMUNITY_SECTION_LABEL", value: "커뮤니티 인기 글", description: "대시보드 섹션" },
  { key: "DASHBOARD_METRIC_VALUE_LABEL", value: "{label} {count}", description: "대시보드 라벨" },
  { key: "DASHBOARD_PAGE_BUTTON_LABEL", value: "{page}페이지 보기", description: "대시보드 버튼" },
  { key: "DASHBOARD_POST_OPEN_LABEL", value: "{title} 게시글로 이동", description: "대시보드 라벨" },
  { key: "DASHBOARD_POST_TAGS_LABEL", value: "게시글 태그", description: "대시보드 라벨" },
  { key: "DASHBOARD_PROBLEM_METRICS_LABEL", value: "{problemId} 추천 지표", description: "대시보드 라벨" },
  { key: "DASHBOARD_PROBLEM_NEXT_BUTTON_LABEL", value: "다음 추천 문제 보기", description: "대시보드 버튼" },
  { key: "DASHBOARD_PROBLEM_OPEN_LABEL", value: "{problemId} 문제로 이동", description: "대시보드 라벨" },
  { key: "DASHBOARD_PROBLEM_PAGE_LABEL", value: "문제 추천 페이지 선택", description: "대시보드 페이지" },
  { key: "DASHBOARD_PROBLEM_PREVIOUS_BUTTON_LABEL", value: "이전 추천 문제 보기", description: "대시보드 버튼" },
  { key: "DASHBOARD_PROBLEM_SECTION_LABEL", value: "문제 추천", description: "대시보드 섹션" },
  { key: "FAVORITE_PAGE_EMPTY_STATE", value: "즐겨찾기 된 페이지가 없습니다.", description: "즐겨찾기 빈 상태" },
  { key: "FAVORITE_TABLIST_LABEL", value: "즐겨찾기 탭", description: "즐겨찾기 탭 목록" },
  { key: "HOME_DOMAIN_TABLIST_LABEL", value: "문제 분류 선택", description: "문제 목록 탭 목록" },
  { key: "IMAGE_CROP_ZOOM_LABEL", value: "확대", description: "이미지 자르기 라벨" },
  { key: "PROBLEM_CREATE_PROBLEM_LOADING_LABEL", value: "문제 정보를 불러오는 중입니다.", description: "문제 생성 라벨" },
  { key: "PROBLEM_CREATE_SET_LOADING_LABEL", value: "테이블셋 정보를 불러오는 중입니다.", description: "문제 생성 라벨" },
  { key: "PROBLEM_DETAIL_ERD_ZOOM_IN_LABEL", value: "ERD 확대", description: "문제 상세 라벨" },
  { key: "PROBLEM_DETAIL_ERD_ZOOM_OUT_LABEL", value: "ERD 축소", description: "문제 상세 라벨" },
  { key: "PROBLEM_INFO_CHECKLIST_ALIAS_ITEM", value: "출력 컬럼 순서와 alias를 예시와 맞췄는지 확인하기", description: "문제 정보 출력 컬럼 순서와 alias를 예시와 맞췄는지 확인하기" },
  { key: "PROBLEM_INFO_CHECKLIST_SCAN_ITEM", value: "조건과 조인을 먼저 줄여 불필요한 전체 스캔을 피하기", description: "문제 정보 조건과 조인을 먼저 줄여 불필요한 전체 스캔을 피하기" },
  { key: "PROBLEM_INFO_CHECKLIST_SECTION_TITLE", value: "제출 체크리스트", description: "문제 정보 제목" },
  { key: "PROBLEM_INFO_CHECKLIST_TAGS_ITEM", value: "핵심 키워드 {tags}를 중심으로 풀이 방향 잡기", description: "문제 정보 핵심 키워드 를 중심으로 풀이 방향 잡기" },
  { key: "PROBLEM_INFO_INPUT_EXAMPLE_TITLE", value: "입력 예시", description: "문제 정보 제목" },
  { key: "PROBLEM_INFO_META_LABEL", value: "문제 요약", description: "문제 정보 메타" },
  { key: "PROBLEM_INFO_OUTPUT_EXAMPLE_TITLE", value: "출력 예시", description: "문제 정보 제목" },
  { key: "PROBLEM_INFO_SCHEMA_EMPTY_MESSAGE", value: "테이블 정의를 확인해 주세요.", description: "문제 정보 메시지" },
  { key: "PROBLEM_INFO_SCHEMA_SECTION_TITLE", value: "핵심 스키마", description: "문제 정보 제목" },
  { key: "PROBLEM_INFO_TAG_COUNT_LABEL", value: "태그 {count}개", description: "문제 정보 개수" },
  { key: "PROBLEM_INFO_TITLE", value: "문제 설명", description: "문제 정보 제목" },
  { key: "PROBLEM_TABLE_STATS_COLLAPSE_LABEL", value: "통계 접기", description: "문제 목록 라벨" },
  { key: "PROBLEM_TABLE_STATS_EXPAND_LABEL", value: "통계 펼치기", description: "문제 목록 라벨" },
  { key: "PROFILE_ACTIVITY_COMMENTS_COUNT_LABEL", value: "댓글 {count}", description: "프로필 활동 개수" },
  { key: "PROFILE_ACTIVITY_COMMENT_LABEL", value: "댓글", description: "프로필 활동 라벨" },
  { key: "PROFILE_ACTIVITY_LIKES_COUNT_LABEL", value: "좋아요 {count}", description: "프로필 활동 개수" },
  { key: "PROFILE_ACTIVITY_LOGIN_MOVE_MESSAGE", value: "로그인 후 내 활동 기록 화면으로 이동할 수 있습니다.", description: "프로필 활동 메시지" },
  { key: "PROFILE_ACTIVITY_LOGIN_REQUIRED_DESC", value: "로그인 후 작성한 글, 댓글, 좋아요 기록을 다시 확인해 주세요.", description: "프로필 활동 안내" },
  { key: "PROFILE_ACTIVITY_LOGIN_REQUIRED_TITLE", value: "내 활동 기록을 보려면 로그인이 필요합니다.", description: "프로필 활동 제목" },
  { key: "PROFILE_ACTIVITY_LOGIN_RETURN_MESSAGE", value: "로그인 후 내 활동 기록 화면으로 돌아옵니다.", description: "프로필 활동 메시지" },
  { key: "PROFILE_ACTIVITY_NOT_FOUND_DESC", value: "로그인 후 내 활동 기록을 열거나 Handle 경로로 접근해 주세요.", description: "프로필 활동 안내" },
  { key: "PROFILE_ACTIVITY_NOT_FOUND_TITLE", value: "조회할 활동 기록이 없습니다.", description: "프로필 활동 제목" },
  { key: "PROFILE_ACTIVITY_PAGE_LABEL", value: "활동 기록", description: "프로필 활동 페이지" },
  { key: "PROFILE_ACTIVITY_REPLY_LABEL", value: "대댓글", description: "프로필 활동 라벨" },
  { key: "PROFILE_PAGE_LABEL", value: "프로필", description: "프로필 페이지" },
  { key: "RANKING_DISABLED_BADGE_LABEL", value: "곧 공개", description: "랭킹 준비 라벨" },
  { key: "RANKING_DISABLED_DESC", value: "정답률뿐 아니라 실행 성능까지 반영한 시즌 랭킹과 래더 화면이 추가될 예정입니다.", description: "랭킹 준비 안내" },
  { key: "RANKING_DISABLED_FEATURE_1", value: "성능 점수 기반 시즌 래더", description: "랭킹 준비 항목 1" },
  { key: "RANKING_DISABLED_FEATURE_2", value: "DBMS별 상위 사용자 비교", description: "랭킹 준비 항목 2" },
  { key: "RANKING_DISABLED_FEATURE_3", value: "티어 구간별 통계 리포트", description: "랭킹 준비 항목 3" },
  { key: "RANKING_DISABLED_META_LABEL", value: "준비 중", description: "랭킹 준비 메타" },
  { key: "RESULT_PANEL_BEST_RECORD_LABEL", value: "최고 기록", description: "채점 결과 라벨" },
  { key: "RESULT_PANEL_EMPTY_COMPARISON_MESSAGE", value: "아직 비교할 제출 표본이 없습니다.", description: "채점 결과 메시지" },
  { key: "RESULT_PANEL_ESTIMATED_COST_LABEL", value: "추정 Cost", description: "채점 결과 라벨" },
  { key: "RESULT_PANEL_EXECUTING_HINT_LABEL", value: "{dbms} 기준으로 평가 중", description: "채점 결과 라벨" },
  { key: "RESULT_PANEL_EXECUTION_ENV_LABEL", value: "실행 환경", description: "채점 결과 라벨" },
  { key: "RESULT_PANEL_EXECUTION_TIME_LABEL", value: "실행 시간", description: "채점 결과 라벨" },
  { key: "RESULT_PANEL_FAIL_LABEL", value: "실패", description: "채점 결과 라벨" },
  { key: "RESULT_PANEL_FASTEST_MESSAGE", value: "현재 실행은 최고 기록과 비슷한 속도입니다.", description: "채점 결과 메시지" },
  { key: "RESULT_PANEL_FULL_SCAN_LABEL", value: "전체 스캔", description: "채점 결과 라벨" },
  { key: "RESULT_PANEL_FULL_SCAN_YES_VALUE", value: "발생", description: "채점 결과 값" },
  { key: "RESULT_PANEL_INDEX_UNUSED_VALUE", value: "미활용", description: "채점 결과 값" },
  { key: "RESULT_PANEL_INDEX_USAGE_LABEL", value: "인덱스 사용", description: "채점 결과 라벨" },
  { key: "RESULT_PANEL_INDEX_USED_VALUE", value: "활용됨", description: "채점 결과 값" },
  { key: "RESULT_PANEL_JUDGE_STATUS_LABEL", value: "채점 상태", description: "채점 결과 라벨" },
  { key: "RESULT_PANEL_JUDGE_STATUS_REVIEW_VALUE", value: "재점검 필요", description: "채점 결과 값" },
  { key: "RESULT_PANEL_JUDGE_STATUS_SUCCESS_VALUE", value: "정답 통과", description: "채점 결과 값" },
  { key: "RESULT_PANEL_MEDIAN_LABEL", value: "중앙값", description: "채점 결과 라벨" },
  { key: "RESULT_PANEL_META_LABEL", value: "채점 결과", description: "채점 결과 메타" },
  { key: "RESULT_PANEL_PREVIEW_META_LABEL", value: "결과 미리보기", description: "채점 결과 메타" },
  { key: "RESULT_PANEL_ROW_COUNT_LABEL", value: "{count}행", description: "채점 결과 개수" },
  { key: "RESULT_PANEL_SLOWER_MESSAGE", value: "현재 실행은 중앙값보다 느린 편이며 예상 상위 {topPercent}% 구간입니다.", description: "채점 결과 메시지" },
  { key: "RESULT_PANEL_SUCCESS_LABEL", value: "정답", description: "채점 결과 라벨" },
  { key: "RESULT_PANEL_TITLE", value: "채점 결과", description: "채점 결과 제목" },
  { key: "RESULT_PANEL_TOP_PERCENT_MESSAGE", value: "현재 실행은 예상 상위 {topPercent}% 구간입니다.", description: "채점 결과 메시지" },
  { key: "ROUTER_ACCESS_DENIED_LABEL", value: "권한", description: "라우터 상태 라벨" },
  { key: "ROUTER_ADMIN_ACCESS_DENIED_TITLE", value: "관리자 화면에 접근할 수 없습니다.", description: "라우터 상태 제목" },
  { key: "ROUTER_ADMIN_LOGIN_REQUIRED_MESSAGE", value: "관리자 화면은 권한이 있는 계정으로만 접근할 수 있습니다.", description: "라우터 상태 메시지" },
  { key: "ROUTER_COMMUNITY_EDIT_LOGIN_REQUIRED_TITLE", value: "로그인 후 게시글을 수정할 수 있습니다.", description: "라우터 상태 제목" },
  { key: "ROUTER_COMMUNITY_WRITE_LOGIN_REQUIRED_DESC", value: "커뮤니티 작성 화면은 로그인한 사용자에게만 열립니다.", description: "라우터 상태 안내" },
  { key: "ROUTER_COMMUNITY_WRITE_LOGIN_REQUIRED_TITLE", value: "로그인 후 게시글을 작성할 수 있습니다.", description: "라우터 상태 제목" },
  { key: "ROUTER_COMMUNITY_WRITE_LOGIN_RETURN_MESSAGE", value: "로그인 후 커뮤니티 작성 화면으로 돌아옵니다.", description: "라우터 상태 메시지" },
  { key: "ROUTER_NOT_FOUND_DESC", value: "주소가 바뀌었거나 삭제된 화면입니다. 대시보드에서 다시 이동해 주세요.", description: "라우터 상태 안내" },
  { key: "ROUTER_NOT_FOUND_TITLE", value: "찾을 수 없는 페이지입니다.", description: "라우터 상태 제목" },
  { key: "ROUTER_SESSION_CHECK_DESC", value: "권한과 세션을 확인한 뒤 화면을 엽니다.", description: "라우터 상태 안내" },
  { key: "ROUTER_SESSION_CHECK_TITLE", value: "로그인 상태를 확인하고 있습니다.", description: "라우터 상태 제목" },
  { key: "ROUTER_SESSION_LABEL", value: "세션", description: "라우터 상태 라벨" },
  { key: "SQL_EDITOR_ARIA_LABEL", value: "SQL 에디터", description: "SQL 에디터 접근성 라벨" },
  { key: "SQL_EDITOR_DIRTY_VALUE", value: "수정됨", description: "SQL 에디터 값" },
  { key: "SQL_EDITOR_EXECUTION_ENV_LABEL", value: "실행 환경", description: "SQL 에디터 라벨" },
  { key: "SQL_EDITOR_HELP_PRIMARY", value: "실행은 결과 미리보기와 성능 지표를 빠르게 확인하는 용도이고, 제출은 정답 여부와 성능 조건을 함께 보는 흐름으로 설계했습니다.", description: "SQL 에디터 안내 1" },
  { key: "SQL_EDITOR_HELP_SECONDARY", value: "현재는 목데이터 기반 화면이므로 이후 API를 연결할 때 제출 대기, 히스토리, 실패 로그, 자동 저장 상태를 바로 확장할 수 있습니다.", description: "SQL 에디터 안내 2" },
  { key: "SQL_EDITOR_INITIAL_VALUE", value: "초기 코드", description: "SQL 에디터 값" },
  { key: "SQL_EDITOR_LAST_ACTION_LABEL", value: "최근 액션", description: "SQL 에디터 라벨" },
  { key: "SQL_EDITOR_META_LABEL", value: "SQL 작업 공간", description: "SQL 에디터 메타" },
  { key: "SQL_EDITOR_MOCK_JUDGE_LABEL", value: "모의 채점", description: "SQL 에디터 라벨" },
  { key: "SQL_EDITOR_NO_ACTION_VALUE", value: "아직 실행 전", description: "SQL 에디터 값" },
  { key: "SQL_EDITOR_QUERY_LENGTH_LABEL", value: "쿼리 길이", description: "SQL 에디터 라벨" },
  { key: "SQL_EDITOR_QUERY_LENGTH_VALUE", value: "{lineCount}줄 / {characterCount}자", description: "SQL 에디터 값" },
  { key: "SQL_EDITOR_RESET_BUTTON", value: "초기화", description: "SQL 에디터 버튼" },
  { key: "SQL_EDITOR_RUN_BUTTON", value: "실행", description: "SQL 에디터 버튼" },
  { key: "SQL_EDITOR_STATUS_LABEL", value: "작업 상태", description: "SQL 에디터 라벨" },
  { key: "SQL_EDITOR_SUBMIT_BUTTON", value: "제출", description: "SQL 에디터 버튼" },
  { key: "SQL_EDITOR_TITLE", value: "제출 에디터", description: "SQL 에디터 제목" },
];

export const defaultUiTextMap = defaultUiTexts.reduce<Record<string, DefaultUiTextDefinition>>((map, uiText) => {
  map[uiText.key] = uiText;
  return map;
}, {});
